> ## **Web Scraping Assignment 2 Selenium**
***
**Author : Yashshree Baviskar**

**Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data. This task will be done in following steps:**

- first get the webpage https://www.naukri.com/
- Enter “Data Analyst” in “Skill,Designations,Companies” field and enter “Bangalore” in “enter the location” field.
- Then click the search button.
- Then scrape the data for the first 10 jobs results you get.
- Finally create a dataframe of the scraped data.

Note- All of the above steps have to be done in code. No step is to be done manually.

In [35]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException


import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [36]:
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver

In [37]:
# Opening naukri.com
url ='https://www.naukri.com/'
driver.get(url)

time.sleep(15)

Sending Input as “Data Analyst” in “Skill,Designations,Companies” field and “Bangalore” in “enter the location” field.

In [38]:
time.sleep(15)
search_job= driver.find_element_by_class_name("suggestor-input")

search_job

In [39]:
time.sleep(14)
search_job.send_keys("Data Analyst")

In [40]:
time.sleep(13)
search_location=driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[3]/div/div/div[3]/div/div/div/input')
search_location

In [41]:
time.sleep(13)
search_location.send_keys("Bangalore")

In [43]:
time.sleep(12)
Search_button=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[6]')
Search_button

In [44]:
time.sleep(12)
title= driver.find_elements_by_xpath('//*[@class="title fw500 ellipsis"]')
len(title)

20

In [45]:
Job_Titles=[]

time.sleep(12)

for i in title:
    Job_Titles.append(i.text)
len(Job_Titles)
Job_Titles[:10]

['Flight data analyst (372)',
 'Senior Data Analyst',
 'Senior Data Analyst',
 'Looking For Data Analyst',
 'software developer & Testing / Business Analyst/Data Analyst/Python.',
 'Staff Business Data Analyst - FDP',
 'Data Analyst - IIM/ISB/MDI/FMS/SP Jain',
 'Senior Data Analyst',
 'Senior Data Analyst',
 'Senior Data Analyst (Digital Services Analytics)']

In [46]:
time.sleep(20)

Company=driver.find_elements_by_xpath('//*[@class="subTitle ellipsis fleft"]')
len(Company)
Company[:10]

[<selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="7e5a2918-046e-458e-a243-878460d7ee43")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="0ab43b2c-9b55-4edc-adf0-4c9acba3a716")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="0103d7ee-37a2-4781-90d3-e3e11276768a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="ec4a3f64-5aec-4d00-871f-0713febdbc2e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="735c661b-a8d5-4a5f-9d0c-c68f4cd7454b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="0186e787-501c-46f7-9557-f694b594d493")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="24b6be5f-2e91-4099-b87c-2c42b00413ca")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="215d30c1-f54b-4a07-b135-972e177f77ef")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="f3872258-7257-4860-b29f-33a413eacd8f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="28eb4d07-381d-4cbf-a08f-d8001b80afca")>]

In [47]:
Company_Names=[]
time.sleep(5)

for i in Company:
    Company_Names.append(i.text)
len(Company_Names)
Company_Names[:10]

['NEST DIGITAL PRIVATE LIMITED',
 'Capco',
 'Mobile Premier League',
 'Trellance',
 'SECRET TECHNOLOGIES INDIA VMS GROUP',
 'Intuit Inc.',
 'K12 Techno Services Pvt Ltd',
 'Flipkart',
 'Flipkart',
 'Dell']

In [48]:
time.sleep(3)
exp=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
exp[0:10]

[<selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="9ff650ac-7f4e-42c4-83d5-10bf40ec1b6b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="148e18e9-c7c5-4e60-8abf-587b7e769b6f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="05d67bd0-23c1-45df-8e42-c0f892e1f8d3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="2716f533-be1c-405b-a281-52bd4fdfed76")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="96380773-e5ce-415d-a47d-67c9983f4f9b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="7264efc3-9231-4557-9ca9-fae5832c1a90")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="9887c0be-6c6c-4f70-9c78-1987a76b3fa5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="a559561a-1880-4676-bdfc-bb58f4c39832")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="8ac1c9b2-7c21-4a14-a720-9ee4cca81e4b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="b3e91b25-9728-444b-8b4e-6fcc58a11e95")>]

In [49]:
Experience=[]
time.sleep(2)
for i in exp:
    Experience.append(i.text)
len(Experience)
time.sleep(3)
Experience[:10]

['0-1 Yrs',
 '4-8 Yrs',
 '3-6 Yrs',
 '0-2 Yrs',
 '0-4 Yrs',
 '5-7 Yrs',
 '4-9 Yrs',
 '3-6 Yrs',
 '3-7 Yrs',
 '1-6 Yrs']

In [50]:
Experience.append("0-0 Yrs")

In [51]:
Experience

['0-1 Yrs',
 '4-8 Yrs',
 '3-6 Yrs',
 '0-2 Yrs',
 '0-4 Yrs',
 '5-7 Yrs',
 '4-9 Yrs',
 '3-6 Yrs',
 '3-7 Yrs',
 '1-6 Yrs',
 '3-8 Yrs',
 '2-6 Yrs',
 '0-1 Yrs',
 '2-7 Yrs',
 '2-4 Yrs',
 '1-2 Yrs',
 '2-5 Yrs',
 '1-2 Yrs',
 '12-15 Yrs',
 '0-0 Yrs']

In [52]:
Job_Location=driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]')
time.sleep(5)
len(Job_Location)
time.sleep(10)
Job_Location[:10]

[<selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="8bb7756b-faa6-47d7-8413-f81f93bd5e70")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="98aa4aad-6c21-4a05-90a7-dedd56295cde")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="f0caca7a-fd34-4e20-9e8a-b0ee8b993506")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="ae86dfd3-a25c-4420-b521-b59a690ac222")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="9cdabf0e-e2f9-40b4-a1d5-4fb87ad03f33")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="89d2bb3c-27e2-41c7-85f6-d4d0d01a659e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="01c61230-d8b9-4ccb-8cd0-67c86b84c826")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="fe7cebbd-57d1-468f-806d-b544d0768e8b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="0765c5a2-b146-4a00-b830-1b406aeb897b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d94b10cf1b290b46418f98c6ba337dd0", element="1af9b7ba-e788-48b3-831a-d822d770296c")>]

In [53]:
Job_Locations=[]
for i in Job_Location:
    Job_Locations.append(i.text)
len(Job_Locations)
time.sleep(5)
Job_Locations[:10]

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Ahmedabad, Bangalore/Bengaluru',
 'Pune, Bangalore/Bengaluru(Shivaji Nagar), Mumbai (All Areas)\n(WFH during Covid)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [54]:
Data_Analyst=pd.DataFrame({})
time.sleep(15)
Data_Analyst['JOB TITLE']=Job_Titles
Data_Analyst['COMPANY']=Company_Names
Data_Analyst['JOB LOCATION']=Job_Locations
Data_Analyst['Experience Require']=Experience
print('Top 10 Data Analyst Job at Banglore :')
Data_Analyst[:10]
time.sleep(10)

Top 10 Data Analyst Job at Banglore :

In [55]:
Data_analyst=pd.DataFrame({})
Data_analyst['JOB TITLE']=Job_Titles
Data_analyst['COMPANY']=Company_Names
Data_analyst['JOB LOCATION']=Job_Locations
Data_analyst['Experience Require']=Experience
print('/033[1m'+'Top 10 Data Analyst Job at Bangrole :'+'/033[0m')
Data_analyst[:10]

/033[1mTop 10 Data Analyst Job at Bangrole :/033[0m

,JOB TITLE,COMPANY,JOB LOCATION,Experience Require
0,Flight data analyst (372),NEST DIGITAL PRIVATE LIMITED,Bangalore/Bengaluru,0-1 Yrs
1,Senior Data Analyst,Capco,Bangalore/Bengaluru,4-8 Yrs
2,Senior Data Analyst,Mobile Premier League,Bangalore/Bengaluru,3-6 Yrs
3,Looking For Data Analyst,Trellance,"Ahmedabad, Bangalore/Bengaluru",0-2 Yrs
4,software developer & Testing / Business Analys...,SECRET TECHNOLOGIES INDIA VMS GROUP,"Pune, Bangalore/Bengaluru(Shivaji Nagar), Mumb...",0-4 Yrs
5,Staff Business Data Analyst - FDP,Intuit Inc.,Bangalore/Bengaluru,5-7 Yrs
6,Data Analyst - IIM/ISB/MDI/FMS/SP Jain,K12 Techno Services Pvt Ltd,Bangalore/Bengaluru,4-9 Yrs
7,Senior Data Analyst,Flipkart,Bangalore/Bengaluru,3-6 Yrs
8,Senior Data Analyst,Flipkart,Bangalore/Bengaluru,3-7 Yrs
9,Senior Data Analyst (Digital Services Analytics),Dell,Bangalore/Bengaluru,1-6 Yrs

**Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You
have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data.
This task will be done in following steps:**

1. First get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, Companies” field and enter “Bangalore” in “enter the
location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.

Note: All of the above steps have to be done in code. No step is to be done manually

In [57]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver
time.sleep(5)

In [58]:
# Opening naukri.com
url ='https://www.naukri.com/'
driver.get(url)
time.sleep(5)

In [59]:
search_job= driver.find_element_by_class_name("suggestor-input")
search_job
time.sleep(5)
search_job.send_keys("Data Scientist")
time.sleep(5)

In [60]:
search_location=driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[3]/div/div/div[3]/div/div/div/input')
search_location
time.sleep(5)
search_location.send_keys("Bangalore")

In [61]:
Search_button=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[6]')
Search_button
time.sleep(2)

In [62]:
title= driver.find_elements_by_xpath('//*[@class="title fw500 ellipsis"]')
len(title)
time.sleep(5)
Job_Titles=[]

for i in title:
    Job_Titles.append(i.text)
len(Job_Titles)
Job_Titles[:10]

['Data Scientist / Analyst',
 'Senior Data Scientist',
 'Data Scientist II- Merchandise & Discovery',
 'Forecasting Analyst/ Data Scientist (US Client)',
 'Consultant - Junior Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Principal Data Scientist',
 'Excellent Opportunity For Freshers For AI/ML, Data Scientist, BI, QA',
 'Junior Data Scientist']

In [63]:
exp=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
exp
time.sleep(5)
Experience=[]
for i in exp:
    Experience.append(i.text)
len(Experience)
Experience[:10]

['4-9 Yrs',
 '5-10 Yrs',
 '2-5 Yrs',
 '3-8 Yrs',
 '2-7 Yrs',
 '4-6 Yrs',
 '5-10 Yrs',
 '7-11 Yrs',
 '0-0 Yrs',
 '1-5 Yrs']

In [73]:
Job_Location=driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]')
time.sleep(5)
Job_Location

[<selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="dbfea55e-54c2-4d38-a74b-17837c07449d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="46103ac6-f748-4dc4-8f4e-8a35c11659cf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="60c829bc-6e56-4809-bf42-e24a0c40d579")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="722946fc-43b0-4a28-b21b-05de1d71f35d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="54bffaf3-f2ca-4707-a811-1a24a8d9ef3f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="d7ea288a-0d33-4c35-897e-114515f4b793")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="00883ad5-4ca2-4383-bdff-120947110696")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="c1079e3b-c754-4886-984b-33a0dad8bd40")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="d1fbbd0f-fab1-4b28-b278-db151915b69f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="6ffc0498-258b-442d-b7d2-40921215b8db")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="508f8317-b474-4050-9e85-81502f97f781")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="8dff0b9a-bcee-4fd8-9e28-7c21f68280b9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="9efddab0-697e-491e-8a8a-1cf351c7a35e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="9393036a-4254-4910-b8a1-bc6d60b61cd9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="e5200865-ce0d-4652-a0e7-a52dbbe47655")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="bba2a33e-e380-478e-9862-c660375e4128")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="86de0011-3034-434f-8f63-b68789b12efe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="89fe45e7-9840-451f-98e3-44b95eb24f54")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="0f4c4f17-4955-4dd5-af85-dddbe49baea8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="820bc339c462ea23a40746a5dbbd77d5", element="ffb1ae6a-1ba8-4315-b780-5a738e9b28ef")>]

In [74]:
Job_Locations=[]
for i in Job_Location:
    Job_Locations.append(i.text)
len(Job_Locations)
Job_Locations[:10]

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Gurgaon/Gurugram, Bangalore/Bengaluru\n(WFH during Covid)',
 'Navi Mumbai, New Delhi, Bangalore/Bengaluru',
 'Chennai, Bangalore/Bengaluru\n(WFH during Covid)',
 'Bangalore/Bengaluru',
 'Chennai, Bangalore/Bengaluru\n(WFH during Covid)',
 'Noida, Kolkata, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)\n(WFH during Covid)',
 'Bangalore/Bengaluru']

In [75]:
Data_Scientist=pd.DataFrame({})
Data_Scientist['JOB TITLE']=Job_Titles
Data_Scientist['COMPANY']=Company_Names
Data_Scientist['JOB LOCATION']=Job_Locations
Data_Scientist['Experience Require']=Experience
print('Top 10 Data Scientist in Bangrole :')
Data_Scientist[:10]

Top 10 Data Scientist in Bangrole :

,JOB TITLE,COMPANY,JOB LOCATION,Experience Require
0,Data Scientist / Analyst,NEST DIGITAL PRIVATE LIMITED,Bangalore/Bengaluru,4-9 Yrs
1,Senior Data Scientist,Capco,Bangalore/Bengaluru,5-10 Yrs
2,Data Scientist II- Merchandise & Discovery,Mobile Premier League,Bangalore/Bengaluru,2-5 Yrs
3,Forecasting Analyst/ Data Scientist (US Client),Trellance,"Gurgaon/Gurugram, Bangalore/Bengaluru\n(WFH du...",3-8 Yrs
4,Consultant - Junior Data Scientist,SECRET TECHNOLOGIES INDIA VMS GROUP,"Navi Mumbai, New Delhi, Bangalore/Bengaluru",2-7 Yrs
5,Data Scientist,Intuit Inc.,"Chennai, Bangalore/Bengaluru\n(WFH during Covid)",4-6 Yrs
6,Data Scientist,K12 Techno Services Pvt Ltd,Bangalore/Bengaluru,5-10 Yrs
7,Principal Data Scientist,Flipkart,"Chennai, Bangalore/Bengaluru\n(WFH during Covid)",7-11 Yrs
8,"Excellent Opportunity For Freshers For AI/ML, ...",Flipkart,"Noida, Kolkata, Hyderabad/Secunderabad, Pune, ...",0-0 Yrs
9,Junior Data Scientist,Dell,Bangalore/Bengaluru,1-5 Yrs

**Q3.In this question you have to scrape data using the filters available on the webpage as shown below:
You have to use the location and salary filter.You have to scrape data for “Data Scientist” designation for first 10 job results. You have to scrape the job-title, job-location, company name, experience required.The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs The task will be done as shown in the below steps:**

1. first get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, and Companies” field.
3. Then click the search button.
4. Then apply the location filter and salary filter by checking the respective boxes
5. Then scrape the data for the first 10 jobs results you get.
6. Finally create a dataframe of the scraped data.

Note: All of the above steps have to be done in code. No step is to be done manually

In [2]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver
# Opening naukri.com
url ='https://www.naukri.com/'
driver.get(url)

In [3]:
search_job= driver.find_element_by_class_name("suggestor-input")
search_job.send_keys("Data Scientist")
time.sleep(3)

In [4]:
search_location=driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[3]/div/div/div[3]/div/div/div/input')
search_location.send_keys("Delhi/NCR")
time.sleep(2)

In [6]:
Search_button=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div[1]/div[6]')
Search_button.click()
time.sleep(2)

In [8]:
Salary_button=driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[4]/div[2]/div[2]/label/p/span[1]')
Salary_button.click()
time.sleep(2)

In [9]:
title= driver.find_elements_by_xpath('//*[@class="title fw500 ellipsis"]')
time.sleep(3)

In [10]:
Job_Titles=[]
for i in title:
    Job_Titles.append(i.text)
else:
    Job_Titles.append('-')

In [12]:
exp=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")

In [13]:
Experience=[]
for i in exp:
    Experience.append(i.text)
else:
    Experience.append('-')    
time.sleep(1)

In [14]:
Job_Location=driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]')

In [15]:
Job_Locations=[]
for i in Job_Location:   
    Job_Locations.append(i.text)
else:
    Job_Locations.append('-')

In [17]:
company_Names=driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]')
Company_Names=[]
for i in company_Names:
    Company_Names.append(i.text)
else:
    Company_Names.append('-')    
time.sleep(1)

In [18]:
Data_Scientist=pd.DataFrame({})
Data_Scientist['JOB TITLE']=Job_Titles[:10]
Data_Scientist['COMPANY']=Company_Names[:10]
Data_Scientist['JOB LOCATION']=Job_Locations[:10]
Data_Scientist['Experience Require']=Experience[:10]
print('Top 10 Data Scientist in Delhi/NCR :')
Data_Scientist

Top 10 Data Scientist in Delhi/NCR :

,JOB TITLE,COMPANY,JOB LOCATION,Experience Require
0,Hiring For Senior Data Scientist-Noida,Lumiq.ai,"Noida, New Delhi, Greater Noida",2-6 Yrs
1,"Excellent Opportunity For Freshers For AI/ML, ...",NTT Data,"Noida, Kolkata, Hyderabad/Secunderabad, Pune, ...",0-0 Yrs
2,Data Analyst / Data Scientist / Business Analy...,GABA Consultancy services,"Noida, New Delhi, Delhi / NCR",0-0 Yrs
3,Data scientist- Python,TeamPlus Staffing Solution Pvt Ltd,Gurgaon/Gurugram,3-6 Yrs
4,Data Scientist _NLP,EXL,"Bangalore/Bengaluru, Delhi / NCR\n(WFH during ...",3-8 Yrs
5,Data Scientist,Mount Talent Consulting Private Limited,"Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram...",1-4 Yrs
6,Lead Data Scientist,Indihire HR Consultants Private Limited,Delhi / NCR\n(WFH during Covid),2-4 Yrs
7,Data Scientist (freelance),2Coms,"New Delhi, Delhi",2-7 Yrs
8,Only Fresher / Python Data Scientist / Trainee...,GABA Consultancy services,"Noida, New Delhi, Gurgaon/Gurugram",0-0 Yrs
9,Hiring For Data Scientist- Gurgaon/ Noida,Mascot e-services,"Noida, Gurgaon/Gurugram",2-4 Yrs

**Q4: Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes:
Brand
Product Description
Price
Discount %
The attributes which you have to scrape is ticked marked in the below image.**

To scrape the data you have to go through following steps:

Go to flipkart webpage by url https://www.flipkart.com/

Enter “sunglasses” in the search field where “search for products, brands and more” is written and click the search icon

after that you will reach to a webpage having a lot of sunglasses. From this page you can scrap the required data as usual.

after scraping data from the first page, go to the “Next” Button at the bottom of the page , then click on it.

Now scrape data from this page as usual

repeat this until you get data for 100 sunglasses.

Note that all of the above steps have to be done by coding only and not manually.

In [93]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
# connecting Webdriver
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver
# Opening naukri.com
url ='https://www.flipkart.com/'
driver.get(url)

In [94]:
driver.find_element_by_xpath('//div[@class="_3OO5Xc"]/input').send_keys('sunglasses')
driver.find_element_by_xpath('//button[@class="L0Z3Pu"]').click()

In [95]:
#creating the empty lists
Brand=[]
Product_Description=[]
Price=[]
Discount=[]

In [96]:
# Scraping URl of 100 Sunglasses
URL=[]
for i in range(0,3):
    S_g_url=driver.find_elements_by_xpath('//a[@class="_2UzuFa"]')
    for i in S_g_url:
        URL.append(i.get_attribute('href'))
    # Clicking on NEXT button at end of page
    driver.find_element_by_xpath('//a[@class="_1LKTO3"]').click()
    time.sleep(4)

In [97]:
URL[:100]

['https://www.flipkart.com/crystal-cart-oval-sunglasses/p/itmb5f6d42d884a8?pid=SGLG7SJGBFMZSQC4&lid=LSTSGLG7SJGBFMZSQC4IWM55X&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_1&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCXsCKI18V5pe9s2UJ2PBlcnoKHPfnVA5AlTMsol2EDfMQ%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/rozzetta-craft-rectangular-sunglasses/p/itm7c7f15b2328e4?pid=SGLGB7UVGKERNGEH&lid=LSTSGLGB7UVGKERNGEH4JURBR&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_2&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCXLyWtO3ufFwSOeirLu9KFr%2FHRwbkA%2FlckE3AJr0rkbbg%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/srpm-wayfarer-sunglasses/p/itmaf19ae5820c06?pid=SGLFHQPHY2GZ4HFP&lid=LSTSGLFHQPHY2GZ4HFP0AZWKY&marketplace=FLIPKART&q=sunglasses&store=26x&spotlightTagId=BestsellerId_26x&srno=s_1_3&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFHQPHY2GZ4HFP.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/sunbee-wayfarer-sunglasses/p/itm0ec82c2e7927f?pid=SGLG3FTNVJFX45YX&lid=LSTSGLG3FTNVJFX45YX2YSY8S&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_4&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLG3FTNVJFX45YX.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/piraso-aviator-sunglasses/p/itm70504d13b7992?pid=SGLFV8YYCEA8RWAC&lid=LSTSGLFV8YYCEA8RWACIACICJ&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_5&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFV8YYCEA8RWAC.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/elligator-round-sunglasses/p/itm3c981fc444358?pid=SGLFPHP5BVBJTCDB&lid=LSTSGLFPHP5BVBJTCDB7P4T6G&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_6&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFPHP5BVBJTCDB.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/new-specs-rectangular-sunglasses/p/itm545a0f9e323c3?pid=SGLG2ESNVFBGD6NQ&lid=LSTSGLG2ESNVFBGD6NQDMTXPL&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_7&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLG2ESNVFBGD6NQ.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/rozzetta-craft-rectangular-sunglasses/p/itmc07cb7e8aec50?pid=SGLFSZV6PXGZGZGX&lid=LSTSGLFSZV6PXGZGZGXNWELSX&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_8&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCWWE2xVlpP83wFWw4sGaTKs8tDhAIbmzbNUR1%2BFFY6qyQ%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/deixels-aviator-wayfarer-sunglasses/p/itmf3yke7n2axuym?pid=SGLF2YZXCDM6QACV&lid=LSTSGLF2YZXCDM6QACV8HRV24&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_9&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLF2YZXCDM6QACV.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/shaah-collections-rectangular-sunglasses/p/itm201340b1c3e13?pid=SGLFXWGV5TGFFSPX&lid=LSTSGLFXWGV5TGFFSPXSORUG9&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_10&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFXWGV5TGFFSPX.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/fastrack-wayfarer-sunglasses/p/itm7dda9b565d045?pid=SGLFG94C8PAHZ3SH&lid=LSTSGLFG94C8PAHZ3SHAFCJXO&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_11&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFG94C8PAHZ3SH.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/pc-star-rectangular-sunglasses/p/itm9731ab2ec615e?pid=SGLGFAYUZYPDT2T9&lid=LSTSGLGFAYUZYPDT2T9JFT5WE&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_12&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCXUGGRzo%2BbOJamppUBz4wwts807mfgZAc1dDjkiTlGcdQ%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/fastrack-rectangular-sunglasses/p/itm3c6e13efc17e0?pid=SGLES2WMF6CH5GYF&lid=LSTSGLES2WMF6CH5GYFXRVSZN&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_13&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLES2WMF6CH5GYF.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/lee-topper-wrap-around-sunglasses/p/itmf0420cbc019f0?pid=SGLFKA8FVYBCGFGC&lid=LSTSGLFKA8FVYBCGFGCTFQA86&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_14&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFKA8FVYBCGFGC.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/piraso-aviator-sunglasses/p/itm4210bb67b2728?pid=SGLFPFD7WRNASWSV&lid=LSTSGLFPFD7WRNASWSVJLGDDX&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_15&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFPFD7WRNASWSV.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/sewell-butterfly-sunglasses/p/itm39e0618d9cf67?pid=SGLFYPNBPBYNT4BM&lid=LSTSGLFYPNBPBYNT4BMEORYRH&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_16&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCVPV5wUHbSHsieG%2BMkrlQscolIFqS%2Bf3rxTKlosa6Ix2A%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/sunbee-round-sunglasses/p/itmb550c957e1689?pid=SGLFUHKVTHSJMKTM&lid=LSTSGLFUHKVTHSJMKTMTM6LJ0&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_17&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFUHKVTHSJMKTM.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/kingsunglasses-wayfarer-sunglasses/p/itmb42161fdc7626?pid=SGLFTUBUZUNHHWPQ&lid=LSTSGLFTUBUZUNHHWPQ3RZ2KW&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_18&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFTUBUZUNHHWPQ.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/srpm-wayfarer-retro-square-sunglasses/p/itmbbc3f64245c43?pid=SGLFY8HAHTSNHHHR&lid=LSTSGLFY8HAHTSNHHHRZFLP9I&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_19&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFY8HAHTSNHHHR.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/skyza-india-sports-sunglasses/p/itm8f67f738419ff?pid=SGLG9D3QFTCKDF9B&lid=LSTSGLG9D3QFTCKDF9BMNUKUD&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_20&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCWZZfQPIfYGxlqBcLYCylkt8XZXdJjtsIg6QHXMUhvPcg%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/piraso-wayfarer-sunglasses/p/itm8b4f0ab184f40?pid=SGLFGAD4R4HZGEKD&lid=LSTSGLFGAD4R4HZGEKDWW1HBB&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_21&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFGAD4R4HZGEKD.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/lee-topper-rectangular-sunglasses/p/itmdc0e4ca417b38?pid=SGLG9Y9ZBWUSGWAC&lid=LSTSGLG9Y9ZBWUSGWACKEXS2L&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_22&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLG9Y9ZBWUSGWAC.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/shaah-collections-rectangular-sunglasses/p/itm98878a113520c?pid=SGLFXXKC3RYXQWFG&lid=LSTSGLFXXKC3RYXQWFGB3OAUU&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_23&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFXXKC3RYXQWFG.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/royal-son-round-sunglasses/p/itm87d9e17e6a738?pid=SGLFZUMCWBDQC8PH&lid=LSTSGLFZUMCWBDQC8PHMXNXNG&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_24&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCUAtTUdgIbpsBx8R%2Bj4ZhboU8dyp77SPxN340M6SMW2WA%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/royal-son-aviator-sunglasses/p/itme479614d796cc?pid=SGLED3YH6AQQFTJT&lid=LSTSGLED3YH6AQQFTJTD9JARU&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_25&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLED3YH6AQQFTJT.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/gansta-wayfarer-sunglasses/p/itm58e84823a6ef0?pid=SGLFV5HSGFYEYMVC&lid=LSTSGLFV5HSGFYEYMVCIQJYRJ&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_26&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFV5HSGFYEYMVC.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/phenomenal-retro-square-sunglasses/p/itm46281b2ac57db?pid=SGLG75ZJFEH3EEUU&lid=LSTSGLG75ZJFEH3EEUUXRLEW5&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_27&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLG75ZJFEH3EEUU.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/rozzetta-craft-rectangular-sunglasses/p/itm7e717fb4e4af0?pid=SGLFX84MT48ZH7RZ&lid=LSTSGLFX84MT48ZH7RZPN64SZ&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_28&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCWx%2B1zznucNUwg26cFIcEmT1HEHkLTKcifEbXhFijkWZw%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/new-specs-round-sunglasses/p/itm02fdce83770d3?pid=SGLFTDG2NSHTKBFF&lid=LSTSGLFTDG2NSHTKBFFWKBAV2&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_29&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFTDG2NSHTKBFF.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/piraso-aviator-sunglasses/p/itm405062704fcc0?pid=SGLFTYY5NWNKSC64&lid=LSTSGLFTYY5NWNKSC64YLGIVW&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_30&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFTYY5NWNKSC64.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/rozzetta-craft-sports-wrap-around-sunglasses/p/itm10af50b049674?pid=SGLG9AFQF2HNHK7A&lid=LSTSGLG9AFQF2HNHK7AIIXH1I&marketplace=FLIPKART&q=sunglasses&store=26x&spotlightTagId=TrendingId_26x&srno=s_1_31&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLG9AFQF2HNHK7A.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/aislin-cat-eye-sunglasses/p/itm097ec81d25c77?pid=SGLFRGT79QE8WFHZ&lid=LSTSGLFRGT79QE8WFHZBH5URU&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_32&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCU%2Bg95QTmO%2BZOiZZCMWG08j%2BG7a%2Flf9D9QjNdOLa7vw8A%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/elligator-round-sunglasses/p/itmfhsbqywv36y54?pid=SGLFHRKF5GPR6ZBY&lid=LSTSGLFHRKF5GPR6ZBY1Z1BRU&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_33&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFHRKF5GPR6ZBY.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/kingsunglasses-round-sunglasses/p/itmfb9juuhzg79rv?pid=SGLFB9GQVKJZGNDG&lid=LSTSGLFB9GQVKJZGNDGR9GRCM&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_34&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFB9GQVKJZGNDG.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/piraso-aviator-sunglasses/p/itma9ed6fe9b3b86?pid=SGLFZJQUNAHYUCAS&lid=LSTSGLFZJQUNAHYUCASKDXKTE&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_35&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFZJQUNAHYUCAS.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/rozzetta-craft-retro-square-sunglasses/p/itm625089b9ccb46?pid=SGLGYKH9PUMJBCZF&lid=LSTSGLGYKH9PUMJBCZFHUCV6F&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_36&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCUZi9wD%2Bz6U%2BUpWQLfjs5AbnlW%2FutFGqgkocrFUXzBlmQ%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/kingsunglasses-wayfarer-sunglasses/p/itm9c7287be7c247?pid=SGLG2ZY9UERPGCZX&lid=LSTSGLG2ZY9UERPGCZXOWQRMA&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_37&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLG2ZY9UERPGCZX.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/kingsunglasses-wayfarer-rectangular-sunglasses/p/itm9f3395eb32fae?pid=SGLG3ZGYTNE5AWAP&lid=LSTSGLG3ZGYTNE5AWAP7HHAAM&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_38&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLG3ZGYTNE5AWAP.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/rich-club-round-sunglasses/p/itmfavsvf2n4navw?pid=SGLFAVKP2UPXZUPX&lid=LSTSGLFAVKP2UPXZUPXLCHQ5V&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_39&otracker=search&otracker1=search&fm=Search&iid=140762a3-92c5-432c-929a-37eff2b4e35b.SGLFAVKP2UPXZUPX.SEARCH&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/royal-son-over-sized-sunglasses/p/itmd2c1be0d69d30?pid=SGLG3PHATP4MGGZU&lid=LSTSGLG3PHATP4MGGZUUGVNU6&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_1_40&otracker=search&otracker1=search&fm=Search&iid=en_u%2FP1piBVce9DmTcqrEiVZDtnWL4Ru%2FBguqeX8IZVMCUcIkTZrfJjUuVoqmVhYzuNvlL7hIg%2Floh0hFHd8hXR4A%3D%3D&ppt=hp&ppn=homepage&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/rich-club-round-sunglasses/p/itmfavsvf2n4navw?pid=SGLFAVKP2UPXZUPX&lid=LSTSGLFAVKP2UPXZUPXLCHQ5V&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_41&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLFAVKP2UPXZUPX.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/kingsunglasses-wayfarer-sunglasses/p/itm357a4bd95bf39?pid=SGLG66ZNGUJ9YBZZ&lid=LSTSGLG66ZNGUJ9YBZZUUCIAZ&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_42&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLG66ZNGUJ9YBZZ.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/kingsunglasses-wayfarer-rectangular-sunglasses/p/itm9f3395eb32fae?pid=SGLG3ZGYTNE5AWAP&lid=LSTSGLG3ZGYTNE5AWAP7HHAAM&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_43&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLG3ZGYTNE5AWAP.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/crystal-cart-round-sunglasses/p/itm1f0888a9280ce?pid=SGLG2GB8QWS9BRDT&lid=LSTSGLG2GB8QWS9BRDTA5N1MI&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_44&otracker=search&otracker1=search&fm=Search&iid=en_34lzCJmfohtbf%2B0clrh87LKm6NgvNXXl%2B9rLAiTmVU7WVCxXdzFIZKSdmTvStKh3V%2FOCLtDDua6mNeeDdqP5ZQ%3D%3D&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/new-specs-sports-sunglasses/p/itme5079a93a9a9d?pid=SGLG8V3ZCGGUWBMX&lid=LSTSGLG8V3ZCGGUWBMXPYDP7V&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_45&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLG8V3ZCGGUWBMX.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/fastrack-wayfarer-sunglasses/p/itm21c980ee51600?pid=SGLFG94CXYTBH8XR&lid=LSTSGLFG94CXYTBH8XR0WNU9P&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_46&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLFG94CXYTBH8XR.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/silver-kartz-wayfarer-sunglasses/p/itmf3ykz37jypbdd?pid=SGLEXSP4CY6G2ZTY&lid=LSTSGLEXSP4CY6G2ZTYGHVAAN&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_47&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLEXSP4CY6G2ZTY.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/izaan-mart-rectangular-sunglasses/p/itmf6aac2bf1baff?pid=SGLG37NJWYPSYSQZ&lid=LSTSGLG37NJWYPSYSQZA9GZRA&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_48&otracker=search&otracker1=search&fm=Search&iid=en_34lzCJmfohtbf%2B0clrh87LKm6NgvNXXl%2B9rLAiTmVU4oE25zQnq8q%2Bckw6F0RanqOJK%2FcHxbZfdG0WdshVMAKQ%3D%3D&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/sunbee-retro-square-sunglasses/p/itmb89a15e6ca52a?pid=SGLG3HZUQWBQTKMZ&lid=LSTSGLG3HZUQWBQTKMZIWGU63&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_49&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLG3HZUQWBQTKMZ.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/srpm-wayfarer-sunglasses/p/itm72f1335147fe2?pid=SGLFGBCAWZHBUPCZ&lid=LSTSGLFGBCAWZHBUPCZTIHSGU&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_50&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLFGBCAWZHBUPCZ.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/phenomenal-retro-square-sunglasses/p/itm1ead9ddbbb3d8?pid=SGLFUBFWNBFEAVD3&lid=LSTSGLFUBFWNBFEAVD31E0HIC&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_51&otracker=search&otracker1=search&fm=Search&iid=abce67c1-c81c-4dc2-a741-c52c1c8737d0.SGLFUBFWNBFEAVD3.SEARCH&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',
 'https://www.flipkart.com/royal-son-aviator-sunglasses/p/itm4d6aae13a0d95?pid=SGLFT7RYYMQPNHZM&lid=LSTSGLFT7RYYMQPNHZMEXDMCZ&marketplace=FLIPKART&q=sunglasses&store=26x&srno=s_2_52&otracker=search&otracker1=search&fm=Search&iid=en_34lzCJmfohtbf%2B0clrh87LKm6NgvNXXl%2B9rLAiTmVU4TElnEC66b3k7mT0Vf6eJLJdSntDB%2FJbF5Q8mMEG%2Bndg%3D%3D&ppt=sp&ppn=sp&ssid=crpxqptxo00000001647155444194&qH=2cc465e3eef5bff0',

In [98]:
for i in URL[:100]:
    driver.get(i)
    try:
        brand=driver.find_element_by_xpath("//span[@class='G6XhRU']").text
        Brand.append(brand)
        description=driver.find_element_by_xpath("//span[@class='B_NuCI']").text
        Product_Description.append(description)
        price=driver.find_element_by_xpath("//div[@class='_30jeq3 _16Jk6d']").text
        Price.append(price)
        discount=driver.find_element_by_xpath("//div[@class='_3Ay6Sb _31Dcoz pZkvcx']/span").text
        Discount.append(discount)
    except NoSuchElementException:
        Brand.append("NaN")
        Product_Description.append("NaN")
        Price.append("NaN")
        Discount.append('NaN')

In [99]:
Sunglasses=pd.DataFrame({})
Sunglasses['Brand']=Brand[:100]
Sunglasses['Product_Description']=Product_Description[:100]
Sunglasses['Price']=Price[:100]
Sunglasses['Discount']=Discount[:100]

Sunglasses

,Brand,Product_Description,Price,Discount
0,CRYSTAL CART,"Mirrored, Night Vision Oval Sunglasses (Free S...",₹92,84% off
1,ROZZETTA CRAFT,"UV Protection, Gradient Rectangular Sunglasses...",₹399,80% off
2,SRPM,UV Protection Wayfarer Sunglasses (50) (For M...,₹148,88% off
3,SUNBEE,"UV Protection, Polarized Wayfarer Sunglasses (...",₹203,84% off
4,PIRASO,UV Protection Aviator Sunglasses (54) (For Me...,₹179,88% off
...,...,...,...,...
95,Sewell,Polarized Butterfly Sunglasses (Free Size) (F...,₹599,70% off
96,SUNBEE,"UV Protection, Polarized, Mirrored Round Sungl...",₹234,86% off
97,kingsunglasses,"UV Protection, Riding Glasses, Mirrored Wayfar...",₹134,88% off
98,PIRASO,UV Protection Wayfarer Sunglasses (32) (For M...,₹175,89% off
99,SKYZA INDIA,"Polarized, UV Protection Sports Sunglasses (Fr...",₹409,77% off

**Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link:
https://www.flipkart.com/apple-iphone-11-black-64-gb-includes- earpods-poweradapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKC
TSVZAXUHGREPBFGI&marketplace.
When you will open the above link you will reach to the below shown webpage .**

 As shown in the above page you have to scrape the tick marked attributes. These are

Rating
Review_summary
Full review
You have to scrape this data for first 100 reviews.

In [111]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
# connecting Webdriver
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver

# Opening naukri.com
url ='https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace'
driver.get(url)

In [112]:
driver.find_element_by_xpath('//div[@class="_3UAT2v _16PBlm"]/span').click()
#creating empty lists
Rating=[]
Review_summary=[]
Full_review=[]

In [115]:
for page in range(1,12):
        
    rat = driver.find_elements_by_xpath('//div[@class="_3LWZlK _1BLPMq"]')
    rev = driver.find_elements_by_xpath('//p[@class="_2-N8zT"]')
    frev= driver.find_elements_by_xpath('//div[@class="t-ZTKy"]')

    for k in rat:
        Rating.append(k.text)

    for i in rev:
        Review_summary.append(i.text)

    for j in frev:
        Full_review.append(j.text)
    time.sleep(3)

    print(len(Review_summary))
    
    nxt_page = driver.find_elements_by_xpath('//a[@class="_1LKTO3"]')
    try:
        driver.get(nxt_page[1].get_attribute('href'))
    except:
        driver.get(nxt_page[0].get_attribute('href'))

20
30
40
50
60
70
80
90
100
110
120

In [117]:
Review_Iphone11= pd.DataFrame({})
Review_Iphone11['Rating'] = Rating[:100]
Review_Iphone11['Review Summary'] = Review_summary[:100] 
Review_Iphone11['Full Review'] = Full_review[:100]
Review_Iphone11.tail()

,Rating,Review Summary,Full Review
95,5,Worth every penny,Nice 👌👌👌👌👌👌
96,5,Mind-blowing purchase,MD sufiyan rider Owsm\nMobile nd battery mast ...
97,3,Highly recommended,"Ok, so after almost 3 years I am again back in..."
98,5,Excellent,Here is the thing\n\nThe only reason why you s...
99,5,Waste of money!,If you are looking for a premium phone under 5...

**Q6: Scrape data for first 100 sneakers you find when you visit flipkart.com andsearch for “sneakers” in the search field. You have to scrape 4 attributes of each sneaker:**
1. Brand
2. Product Description
3. Price
4. discount %

As shown in the below image, you have to scrape the tick marked attributes.

In [119]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

# connecting Webdriver
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver

# Opening naukri.com
url ='https://www.flipkart.com/'
driver.get(url)

In [120]:
driver.find_element_by_xpath('//div[@class="_3OO5Xc"]/input').send_keys('sneakers')
driver.find_element_by_xpath('//button[@class="L0Z3Pu"]').click()

In [121]:
#creating the empty lists
Brand=[]
Product_Description=[]
Price=[]
Discount=[]

In [124]:
url = []
for i in range(0,4):
    lnk = driver.find_elements_by_xpath('//a[@class="_2UzuFa"]')
    for j in lnk:
        url.append(j.get_attribute('href'))
    nxt_page = driver.find_elements_by_xpath('//a[@class="_1LKTO3"]')
    try:
        driver.get(nxt_page[1].get_attribute('href'))
    except:
        driver.get(nxt_page[0].get_attribute('href'))
time.sleep(3)

In [126]:
list_of_url=url[0:100]

In [127]:
from tqdm import tqdm
for i in tqdm(list_of_url):
    driver.get(i)
    try:
        brand=driver.find_element_by_xpath("//span[@class='G6XhRU']").text
        Brand.append(brand)
        description=driver.find_element_by_xpath("//span[@class='B_NuCI']").text
        Product_Description.append(description)
        price=driver.find_element_by_xpath("//div[@class='_30jeq3 _16Jk6d']").text
        Price.append(price)
        discount=driver.find_element_by_xpath("//div[@class='_3Ay6Sb _31Dcoz pZkvcx']/span").text
        Discount.append(discount)
    except NoSuchElementException:
        Brand.append("Null")
        Product_Description.append("Null")
        Price.append("Null")
        Discount.append('Null')
    time.sleep(3)

100%|██████████| 100/100 [10:41<00:00,  6.42s/it]

In [128]:
print(len(Brand),len(Product_Description),len(Price),len(Discount))

100 100 100 100

In [129]:
Sneakers=pd.DataFrame({})
Sneakers['Brand']=Brand[:100]
Sneakers['Product_Description']=Product_Description[:100]
Sneakers['Price']=Price[:100]
Sneakers['Discount']=Discount[:100]
Sneakers

,Brand,Product_Description,Price,Discount
0,Bacan,Sneakers For Men (White),₹476,52% off
1,Numenzo,Sneakers For Men (White),₹599,80% off
2,Kzaara,Sneakers For Men (Grey),₹209,79% off
3,Chevit,Super Stylish & Trendy Combo Pack of 02 Pairs ...,₹469,70% off
4,BRUTON,Modern Trendy Sneakers Shoes Sneakers For Men ...,₹209,83% off
...,...,...,...,...
95,India hub,Luxury Fashionable casual sneaker shoes Sneake...,₹293,85% off
96,luxury fashion,Fashionable sneaker shoes Sneakers For Men (B...,₹449,77% off
97,Rzisbo,Sneakers For Men (Grey),₹549,45% off
98,aadi,"Sneakers For Men (Black, White)",₹269,73% off
99,BRUTON,Combo Pack Of 4 Casual Shoes Loafer Shoes Snea...,₹449,87% off

**Q7: Go to the link - https://www.myntra.com/shoes
Set Price filter to “Rs. 7149 to Rs. 14099 ” , Color filter to “Black”, as shown inthe below image.**

And then scrape First 100 shoes data you get. The data should include “Brand” of the shoes , Short Shoe
description, price of the shoe as shown in the below image.

In [175]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

# connecting Webdriver
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver
#specifying the url of the webpage to be scraped
url="https://www.myntra.com/shoes"
driver.get(url)

In [176]:
#clicking on price filter
driver.find_element_by_xpath('//*[@id="mountRoot"]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label/div').click()

In [178]:
# clicking on color filter
driver.find_element_by_xpath('//*[@id="mountRoot"]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/div').click()

In [179]:
import warnings
warnings.filterwarnings('ignore')

In [180]:
#getting the list of url of first 100 shoes
URL=[]
for i in range(0,2):
    shoes=driver.find_elements_by_xpath("//li[@class='product-base']")
    for i in shoes:
        #shoes1=i.find_element_by_tag_name("div")
        #shoes2=shoes1.find_element_by_tag_name("div")
        shoes3=i.find_element_by_tag_name("a")
        URL.append(shoes3.get_attribute('href'))
    driver.find_element_by_xpath('//*[@id="desktopSearchResults"]/div[2]/section/div[2]/ul/li[3]/a').click()
    time.sleep(3)

In [181]:
URL

['https://www.myntra.com/casual-shoes/aldo/aldo-men-black--blue-printed-sneakers/16297792/buy',
 'https://www.myntra.com/sports-shoes/nike/nike-men-black-zoom-winflo-7-running-shoes/15384892/buy',
 'https://www.myntra.com/sports-shoes/puma/puma-men-black-electrify-nitro-turn-running-shoes/15244656/buy',
 'https://www.myntra.com/casual-shoes/aldo/aldo-men-black-leather-driving-shoes/16859192/buy',
 'https://www.myntra.com/casual-shoes/aldo/aldo-men-black-woven-design-sneakers/16859164/buy',
 'https://www.myntra.com/sports-shoes/puma/puma-men-black-jamming-20-running-shoes/14824822/buy',
 'https://www.myntra.com/sports-shoes/puma/puma-men-black-eternity-nitro-running-shoes/14521968/buy',
 'https://www.myntra.com/formal-shoes/hush-puppies/hush-puppies-men-black-solid-leather-formal-slip-ons/12452162/buy',
 'https://www.myntra.com/casual-shoes/nike/nike-men-black-solid-air-max-dawn-next-nature-regular-sneakers-with-led-lights/16274170/buy',
 'https://www.myntra.com/formal-shoes/hush-puppies/hush-puppies-men-black-solid-leather-formal-slip-ons/12435690/buy',
 'https://www.myntra.com/formal-shoes/hush-puppies/hush-puppies-men-black-solid-formal-derbys-/13123142/buy',
 'https://www.myntra.com/sports-shoes/puma/puma-women-black-textile-eternity-nitro-running-shoes/14850134/buy',
 'https://www.myntra.com/sports-shoes/puma/puma-men-black-blue-fuse-fm-utility-training-or-gym-shoes/15226426/buy',
 'https://www.myntra.com/formal-shoes/hush-puppies/hush-puppies-men-black-solid-leather-formal-derbys/12435696/buy',
 'https://www.myntra.com/sports-shoes/asics/asics-women-black-running-gel-pulse-13-non-marking-shoes/17083878/buy',
 'https://www.myntra.com/formal-shoes/clarks/clarks-men-black-solid-formal-leather-derbys/14866788/buy',
 'https://www.myntra.com/sports-shoes/puma/puma-women-black-velocity-nitro-running-shoes/14850252/buy',
 'https://www.myntra.com/casual-shoes/tommy-hilfiger/tommy-hilfiger-men-black-solid-leather-regular-sneakers-with-cleats/16285696/buy',
 'https://www.myntra.com/sports-shoes/columbia/columbia-men-black-facet-60-outdry-waterproof-non-marking-trekking-shoes/15962552/buy',
 'https://www.myntra.com/formal-shoes/hush-puppies/hush-puppies-men-black-solid-formal-slip-ons/13242280/buy',
 'https://www.myntra.com/formal-shoes/clarks/clarks-men-black-solid-leather-formal-loafers/15759212/buy',
 'https://www.myntra.com/casual-shoes/jfontini/jfontini-men-black-loafers/13343594/buy',
 'https://www.myntra.com/casual-shoes/rare-rabbit/rare-rabbit-men-black-leather-flat-boots/14937476/buy',
 'https://www.myntra.com/formal-shoes/davinchi/davinchi-men-black-textured-formal-leather-loafers/13376942/buy',
 'https://www.myntra.com/heels/aldo/aldo-black-wedge-sandals/16955210/buy',
 'https://www.myntra.com/sports-shoes/triban-by-decathlon/triban-by-decathlon-unisex-black-textile-training-or-gym-non-marking-cycling-shoes/17046426/buy',
 'https://www.myntra.com/sports-shoes/columbia/columbia-women-black--purple-redmond-v2-mid-wp-trekking-non-marking-shoes/15968562/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-women-black--gold-toned-solid-leather-block-heels/11216724/buy',
 'https://www.myntra.com/casual-shoes/clarks/clarks-men-black-leather-derbys/17312246/buy',
 'https://www.myntra.com/casual-shoes/saint-g/saint-g-men-black-solid-mid-top-chelsea-boots/15592368/buy',
 'https://www.myntra.com/casual-shoes/geox/geox-men-black-leather-loafers/15654476/buy',
 'https://www.myntra.com/casual-shoes/geox/geox-men-black-striped-leather-sneakers/16818568/buy',
 'https://www.myntra.com/casual-shoes/jfontini/j-fontini-men-black-solid-leather-loafers/15172434/buy',
 'https://www.myntra.com/formal-shoes/geox/geox-men-black-leather-formal-derbys/16818554/buy',
 'https://www.myntra.com/casual-shoes/hush-puppies/hush-puppies-men-black-perforations-leather-slip-on-sneakers/16470614/buy',
 'https://www.myntra.com/heels/aldo/aldo-black-leather-slim-heels/16955226/buy',
 'https://www.myntra.com/formal-shoes/davinchi/davinchi-men-black-solid-formal-leather-slip-on-shoes/13220574/buy',
 'https://www.myntra.com/formal-shoes/davinchi/ustraa-black/13220578/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-leather-block-heeled-boots/16392876/buy',
 'https://www.myntra.com/heels/geox/geox-women-black-textured-leather-pumps/11107496/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-suede-party-high-top-block-heeled-boots/15949198/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-striped-suede-flatform-heeled-boots/16593054/buy',
 'https://www.myntra.com/casual-shoes/cole-haan/cole-haan-women-black-leather-sneakers/8199511/buy',
 'https://www.myntra.com/heels/geox/geox-women-black-solid-leather-pumps/11107442/buy',
 'https://www.myntra.com/heels/sole-to-soul/sole-to-soul-black-suede-high-top-block-heeled-boots/17363768/buy',
 'https://www.myntra.com/heels/sole-to-soul/sole-to-soul-black-high-top-block-heeled-boots/17363800/buy',
 'https://www.myntra.com/heels/rosso-brunello/rosso-brunello-black-printed-pu-kitten-sandals/17469998/buy',
 'https://www.myntra.com/heels/sole-to-soul/sole-to-soul-black-suede-high-top-block-heeled-boots/17363782/buy',
 'https://www.myntra.com/casual-shoes/fila/fila-women-black-leather-sneakers/16782180/buy',
 'https://www.myntra.com/heels/sole-to-soul/sole-to-soul-black-high-top-comfort-heeled-boots/17363814/buy',
 'https://www.myntra.com/heels/sole-to-soul/sole-to-soul-black-high-top-comfort-heeled-boots/17363814/buy',
 'https://www.myntra.com/heels/rosso-brunello/rosso-brunello-black-pu-block-pumps-with-buckles/17470000/buy',
 'https://www.myntra.com/flats/clarks/clarks-women-black-solid-leather-slip-on-ballerinas/17312552/buy',
 'https://www.myntra.com/flats/clarks/clarks-women-black-solid-leather-ballerina/17312450/buy',
 'https://www.myntra.com/sports-shoes/new-balance/new-balance-women-black-striped-woven-design-running-shoes/15869406/buy',
 'https://www.myntra.com/sports-shoes/columbia/columbia-women-black-peakfreak-xcrsn-ii-xcel-low-outdry-trekking-non-marking-shoes/15968584/buy',
 'https://www.myntra.com/sports-shoes/columbia/columbia-women-black--grey-peakfreak-x2-outdry-trekking-non-marking-shoes/15968606/buy',
 'https://www.myntra.com/formal-shoes/bugatti/bugatti-men-black-solid-formal-oxfords-/17207758/buy',
 'https://www.myntra.com/formal-shoes/churchill--company/churchill--company-men-black-solid-leather-formal-monks/17234672/buy',
 'https://www.myntra.com/sports-shoes/bugatti/bugatti-men-black-textile-walking-non-marking-shoes/15327568/buy',
 'https://www.myntra.com/formal-shoes/bugatti/bugatti-men-black-solid-leather-formal-derbys/17207752/buy',
 'https://www.myntra.com/casual-shoes/geox/geox-men-black-leather-driving-shoes/10029259/buy',
 'https://www.myntra.com/casual-shoes/cole-haan/cole-haan-men-black-originalgrand-stitchlite-wingtip-oxford-sneakers/11052208/buy',
 'https://www.myntra.com/casual-shoes/cole-haan/cole-haan-men-black-generation-zerogrand-stitchlite-sneakers/11052214/buy',
 'https://www.myntra.com/casual-shoes/jfontini/jfontini-men-black-leather-loafers/12681352/buy',
 'https://www.myntra.com/casual-shoes/jfontini/jfontini-men-black-leather-loafers/12681364/buy',
 'https://www.myntra.com/formal-shoes/cobblerz/-cobblerz-men-black-textured-leather-formal-derbys/17370966/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-women-black-woven-leather-block-heel-mules/10236559/buy',
 'https://www.myntra.com/sports-shoes/xtep/xtep-men-black--lime-green-textile-running-non-marking-x-corese-shoes/16179164/buy',
 'https://www.myntra.com/heels/geox/geox-women-black-solid-leather-pumps/11785006/buy',
 'https://www.myntra.com/formal-shoes/heel--buckle-london/heel--buckle-london-men-black-solid-formal-leather-derby/10878318/buy',
 'https://www.myntra.com/flats/cole-haan/cole-haan-women-black-solid-leather-open-toe-flats/10612998/buy',
 'https://www.myntra.com/casual-shoes/cole-haan/cole-haan-women-black-lightweight-sneakers/11046446/buy',
 'https://www.myntra.com/flats/geox/geox-women-black-solid-leather-ballerinas/11107584/buy',
 'https://www.myntra.com/flats/cole-haan/cole-haan-women-black-solid-leather-ballerinas/11426342/buy',
 'https://www.myntra.com/casual-shoes/royal-enfield/royal-enfield-men-black-leather-cabo-wp-riding-boots/15769822/buy',
 'https://www.myntra.com/casual-shoes/asics/asics-men-black--grey-colourblocked-pu-sneakers/15819444/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-women-black-leather-block-heeled-boots-with-chain-embellishment/15216868/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-women-black-leather-high-top-block-heeled-boots/15243094/buy',
 'https://www.myntra.com/formal-shoes/jfontini/jfontini-men-black-solid-leather-formal-loafers/12682166/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-women-black-leather-block-heeled-boots/15242472/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-leather-block-heeled-boots-with-buckles/15216860/buy',
 'https://www.myntra.com/heels/sole-to-soul/sole-to-soul-black--beige-platform-peep-toes-with-buckles/15378636/buy',
 'https://www.myntra.com/heels/bugatti/bugatti-black-block-heeled-boots/15401104/buy',
 'https://www.myntra.com/formal-shoes/jfontini/jfontini-men-black-textured-leather-formal-loafers/12682170/buy',
 'https://www.myntra.com/casual-shoes/pavers-england/pavers-england-men-black-leather-tassel-driving-shoes/16001632/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-leather-kitten-heeled-boots/15801064/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-leather-high-top-block-heeled-boots/15784326/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-leather-wedge-heeled-boots-with-buckles/15784328/buy',
 'https://www.myntra.com/formal-shoes/davinchi/davinchi-men-black-solid-slip-on-shoes/13220650/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-leather-platform-heeled-boots/15946264/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-printed-flatform-heeled-boots-with-buckles/15836458/buy',
 'https://www.myntra.com/formal-shoes/jfontini/jfontini-men-black-solid-leather-formal-loafers/13336352/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-leather-rhinestone-studded-block-heeled-boots-with-bows/15947058/buy',
 'https://www.myntra.com/formal-shoes/jfontini/jfontini-men-black-textured-leather-formal-loafers/13336322/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-suede-leather-high-top-block-heeled-boots/15973270/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-black-suede-high-top-flatform-heeled-boots/16016116/buy',
 'https://www.myntra.com/formal-shoes/davinchi/davinchi-men-black-solid-leather-formal-derbys/13376852/buy',
 'https://www.myntra.com/formal-shoes/davinchi/davinchi-men-black-textured-formal-leather-loafers/13376948/buy',
 'https://www.myntra.com/heels/saint-g/saint-g-women-black-leather-high-top-block-heeled-boots-with-buckles/16015866/buy']

In [185]:
len(URL) # checking length of URL dataset

100

In [190]:
#going to the url of first shoes through our driver
driver.get(URL[0])


#running a loop to extract all the required information from the list_of_url
from tqdm import tqdm
for i in tqdm(URL):
    driver.get(i)
    try:
        brand=driver.find_element_by_xpath('//*[@id="mountRoot"]/div/div/div/main/div[2]/div[2]/div[1]/h1[1]').text
        Brand.append(brand)
    except NoSuchElementException:
        Brand.append("Null")
    try:
        description=driver.find_element_by_xpath('//*[@id="mountRoot"]/div/div/div/main/div[2]/div[2]/div[1]/h1[2]').text
        Product_Description.append(description)
    except NoSuchElementException:
        Product_Description.append("Null")
    try:
        price=driver.find_element_by_xpath('//*[@id="mountRoot"]/div/div/div/main/div[2]/div[2]/div[1]/p[1]/span[1]/strong').text
        Price.append(price)
    except NoSuchElementException:
        Price.append("Null")
    time.sleep(15)

100%|██████████| 100/100 [36:06<00:00, 21.67s/it]

In [197]:
print('\033[1m'+'Price :'+'\033[0m')
Price

Price :

['₹476',
 '₹599',
 '₹209',
 '₹469',
 '₹209',
 '₹148',
 '₹149',
 '₹570',
 '₹249',
 '₹349',
 '₹327',
 '₹590',
 '₹357',
 '₹449',
 '₹190',
 '₹369',
 '₹394',
 '₹249',
 '₹485',
 '₹4,249',
 '₹248',
 '₹349',
 '₹449',
 '₹3,589',
 '₹421',
 '₹499',
 '₹424',
 '₹549',
 '₹293',
 '₹269',
 '₹549',
 '₹433',
 '₹630',
 'Null',
 '₹249',
 '₹349',
 '₹348',
 '₹534',
 '₹261',
 '₹178',
 '₹424',
 '₹199',
 '₹534',
 '₹476',
 '₹424',
 '₹334',
 '₹424',
 '₹357',
 '₹398',
 '₹1,377',
 '₹397',
 '₹599',
 '₹349',
 '₹448',
 '₹630',
 '₹293',
 '₹424',
 '₹394',
 '₹379',
 '₹449',
 '₹349',
 '₹349',
 '₹209',
 '₹570',
 '₹349',
 '₹549',
 '₹799',
 '₹590',
 '₹598',
 '₹398',
 '₹209',
 '₹369',
 '₹347',
 '₹999',
 '₹178',
 '₹4,249',
 '₹249',
 '₹385',
 '₹549',
 '₹433',
 '₹157',
 '₹539',
 '₹424',
 '₹476',
 '₹486',
 '₹349',
 '₹714',
 '₹357',
 '₹399',
 '₹399',
 '₹549',
 '₹599',
 '₹327',
 '₹209',
 '₹765',
 '₹293',
 '₹449',
 '₹549',
 '₹269',
 '₹449',
 'Rs. 1349',
 'Rs. 1199',
 'Rs. 5995',
 'Rs. 4759',
 'Rs. 1374',
 'Rs. 1299',
 'Rs. 15999',
 'Rs. 2749',
 'Rs. 1349',
 'Rs. 3371',
 'Rs. 5395',
 'Rs. 9099',
 'Rs. 899',
 'Rs. 1399',
 'Rs. 1649',
 'Rs. 759',
 'Rs. 7995',
 'Rs. 999',
 'Rs. 374',
 'Rs. 995',
 'Rs. 2199',
 'Rs. 1449',
 'Rs. 1374',
 'Rs. 5436',
 'Rs. 9999',
 'Rs. 9990',
 'Rs. 9990',
 'Rs. 8999',
 'Rs. 7999',
 'Rs. 9499',
 'Rs. 10990',
 'Rs. 8999',
 'Rs. 10990',
 'Rs. 11192',
 'Rs. 7999',
 'Rs. 10990',
 'Rs. 10990',
 'Rs. 6999',
 'Rs. 9999',
 'Rs. 11990',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 11490',
 'Rs. 8999',
 'Rs. 8999',
 'Rs. 12999',
 'Rs. 9999',
 'Rs. 10999',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 10999',
 'Rs. 10490',
 'Rs. 9999',
 'Rs. 12990',
 'Rs. 6499',
 'Rs. 9099',
 'Rs. 7995',
 'Rs. 9999',
 'Rs. 12999',
 'Rs. 13999',
 'Rs. 12999',
 'Rs. 12999',
 'Rs. 7649',
 'Rs. 10995',
 'Rs. 8499',
 'Rs. 8499',
 'Rs. 9099',
 'Rs. 7999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7149',
 'Rs. 8599',
 'Rs. 12999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 8990',
 'Rs. 8099',
 'Rs. 8990',
 'Rs. 7999',
 'Rs. 8029',
 'Rs. 7999',
 'Rs. 7480',
 'Rs. 7499',
 'Rs. 10500',
 'Rs. 9999',
 'Rs. 9990',
 'Rs. 8490',
 'Rs. 9990',
 'Rs. 7999',
 'Rs. 8399',
 'Rs. 8990',
 'Rs. 8990',
 'Rs. 9265',
 'Rs. 8999',
 'Rs. 8925',
 'Rs. 8415',
 'Rs. 10999',
 'Rs. 7999',
 'Rs. 8900',
 'Rs. 7900',
 'Rs. 8499',
 'Rs. 9500',
 'Rs. 8499',
 'Rs. 8900',
 'Rs. 8900',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7149',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 7999',
 'Rs. 7199',
 'Rs. 9499',
 'Rs. 9499',
 'Rs. 12999',
 'Rs. 11999',
 'Rs. 7990',
 'Rs. 8490',
 'Rs. 8999',
 'Rs. 7216',
 'Rs. 7699',
 'Rs. 10990',
 'Rs. 7990',
 'Rs. 11999',
 'Rs. 12999',
 'Rs. 8999',
 'Rs. 13999',
 'Rs. 8500',
 'Rs. 9999',
 'Rs. 12325',
 'Rs. 12325',
 'Rs. 7490',
 'Rs. 14025',
 'Rs. 11815',
 'Rs. 7690',
 'Rs. 7699',
 'Rs. 7490',
 'Rs. 7499',
 'Rs. 9099',
 'Rs. 9099',
 'Rs. 7995',
 'Rs. 9999',
 'Rs. 12999',
 'Rs. 13999',
 'Rs. 12999',
 'Rs. 12999',
 'Rs. 7649',
 'Rs. 10995',
 'Rs. 8499',
 'Rs. 8499',
 'Rs. 9099',
 'Rs. 7999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7149',
 'Rs. 8599',
 'Rs. 12999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 8990',
 'Rs. 8099',
 'Rs. 8990',
 'Rs. 7999',
 'Rs. 8029',
 'Rs. 7999',
 'Rs. 7480',
 'Rs. 7499',
 'Rs. 10500',
 'Rs. 9999',
 'Rs. 9990',
 'Rs. 8490',
 'Rs. 9990',
 'Rs. 7999',
 'Rs. 8399',
 'Rs. 8990',
 'Rs. 8990',
 'Rs. 9265',
 'Rs. 8999',
 'Rs. 8925',
 'Rs. 8415',
 'Rs. 10999',
 'Rs. 7999',
 'Rs. 8900',
 'Rs. 7900',
 'Rs. 8499',
 'Rs. 9500',
 'Rs. 8499',
 'Rs. 8900',
 'Rs. 8900',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7149',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 7999',
 'Rs. 7199',
 'Rs. 9499',
 'Rs. 9499',
 'Rs. 12999',
 'Rs. 11999',
 'Rs. 7990',
 'Rs. 8490',
 'Rs. 8999',
 'Rs. 7216',
 'Rs. 7699',
 'Rs. 10990',
 'Rs. 7990',
 'Rs. 11999',
 'Rs. 12999',
 'Rs. 8999',
 'Rs. 13999',
 'Rs. 8500',
 'Rs. 9999',
 'Rs. 12325',
 'Rs. 12325',
 'Rs. 7490',
 'Rs. 14025',
 'Rs. 11815',
 'Rs. 7690',
 'Rs. 7699',
 'Rs. 7490',
 'Rs. 7499',
 'Rs. 8415',
 'Rs. 14025',
 'Rs. 12665',
 'Rs. 7990',
 'Rs. 9099',
 'Rs. 9099',
 'Rs. 7995',
 'Rs. 9999',
 'Rs. 12999',
 'Rs. 13999',
 'Rs. 12999',
 'Rs. 12999',
 'Rs. 7649',
 'Rs. 10995',
 'Rs. 8499',
 'Rs. 8499',
 'Rs. 9099',
 'Rs. 7999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7149',
 'Rs. 8599',
 'Rs. 12999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 8990',
 'Rs. 8099',
 'Rs. 8990',
 'Rs. 7999',
 'Rs. 8029',
 'Rs. 7999',
 'Rs. 7480',
 'Rs. 7499',
 'Rs. 10500',
 'Rs. 9999',
 'Rs. 9990',
 'Rs. 8490',
 'Rs. 9990',
 'Rs. 7999',
 'Rs. 8399',
 'Rs. 8990',
 'Rs. 8990',
 'Rs. 9265',
 'Rs. 8999',
 'Rs. 8925',
 'Rs. 8415',
 'Rs. 10999',
 'Rs. 7999',
 'Rs. 8900',
 'Rs. 7900',
 'Rs. 8499',
 'Rs. 9500',
 'Rs. 8499',
 'Rs. 8900',
 'Rs. 8900',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7149',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 7999',
 'Rs. 7199',
 'Rs. 9499',
 'Rs. 9499',
 'Rs. 12999',
 'Rs. 11999',
 'Rs. 7990',
 'Rs. 8490',
 'Rs. 8999',
 'Rs. 7216',
 'Rs. 7699',
 'Rs. 10990',
 'Rs. 7990',
 'Rs. 11999',
 'Rs. 9099',
 'Rs. 7995',
 'Rs. 9999',
 'Rs. 12999',
 'Rs. 13999',
 'Rs. 12999',
 'Rs. 12999',
 'Rs. 7649',
 'Rs. 10995',
 'Rs. 8499',
 'Rs. 8499',
 'Rs. 9099',
 'Rs. 7999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 9099',
 'Rs. 7995',
 'Rs. 9999',
 'Rs. 12999',
 'Rs. 13999',
 'Rs. 12999',
 'Rs. 12999',
 'Rs. 7649',
 'Rs. 10995',
 'Rs. 8499',
 'Rs. 8499',
 'Rs. 9099',
 'Rs. 7999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7149',
 'Rs. 8599',
 'Rs. 12999',
 'Rs. 8499',
 'Rs. 7999',
 'Rs. 8990',
 'Rs. 8099',
 'Rs. 8990',
 'Null',
 'Rs. 8029',
 'Rs. 7999',
 'Rs. 7480',
 'Rs. 7499',
 'Rs. 10500',
 'Null',
 'Rs. 9990',
 'Rs. 8490',
 'Rs. 9990',
 'Null',
 'Rs. 8399',
 'Null',
 'Rs. 8990',
 'Rs. 9265',
 'Rs. 8999',
 'Rs. 8925',
 'Rs. 8415',
 'Rs. 10999',
 'Rs. 7999',
 'Rs. 8900',
 'Rs. 7900',
 'Rs. 8499',
 'Rs. 9500',
 'Rs. 8499',
 'Rs. 8900',
 'Rs. 8900',
 'Rs. 7999',
 'Rs. 7999',
 'Rs. 9999',
 'Rs. 7149',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 8999',
 'Rs. 7999',
 'Rs. 7199',
 'Rs. 9499',
 'Rs. 9499',
 'Rs. 12999',
 'Rs. 11999',
 'Rs. 7990',
 'Rs. 8490',
 'Rs. 8999',
 'Rs. 7216',
 'Rs. 7699',
 'Rs. 10990',
 'Rs. 7990',
 'Rs. 11999',
 'Rs. 12999',
 'Rs. 8999',
 'Rs. 13999',
 'Rs. 8500',
 'Rs. 9999',
 'Rs. 12325',
 'Rs. 12325',
 'Rs. 7490',
 'Rs. 14025',
 'Rs. 11815',
 'Rs. 7690',
 'Rs. 7699',
 'Rs. 7490',
 'Rs. 7499',
 'Rs. 8415',
 'Rs. 14025',
 'Rs. 12665',
 'Rs. 7990',
 'Rs. 9265',
 'Rs. 8415',
 'Rs. 9990',
 'Rs. 11815',
 'Null',
 'Rs. 10625',
 'Rs. 11475',
 'Rs. 9990',
 'Rs. 8990',
 'Rs. 8925']

In [198]:
print('\033[1m'+'Brand :'+'\033[0m')
Brand

Brand :

['Bacan ',
 'Numenzo ',
 'Kzaara ',
 'Chevit ',
 'BRUTON ',
 'URBANBOX ',
 'World Wear Footwear ',
 'RapidBox ',
 'BRUTON ',
 'KWIK FIT ',
 'Magnolia ',
 'RapidBox ',
 'luxury fashion ',
 'corsac ',
 'World Wear Footwear ',
 'BIRDE ',
 'Kraasa ',
 'D-SNEAKERZ ',
 'SWIGGY ',
 'SHANE Internation ',
 'Shoes Bank ',
 'Elevarse ',
 'BRUTON ',
 'PUMA ',
 'BRUTON ',
 'Rzisbo ',
 'Labbin ',
 'DoTMaX ',
 'India hub ',
 'aadi ',
 'Vellinto ',
 'Echor ',
 'RapidBox ',
 'Null',
 'BRUTON ',
 'Noztile ',
 'SCATCHITE ',
 'CLYMB ',
 'Zsyto ',
 'Extoes ',
 'Robbie jones ',
 'CLYMB ',
 'CLYMB ',
 'Bacan ',
 'Numenzo ',
 'D-SNEAKERZ ',
 'ASTEROID ',
 'luxury fashion ',
 'Ktiz ',
 'PUMA ',
 'Zorth ',
 'Numenzo ',
 'BAUCHHAAR ',
 'ASIAN ',
 'RapidBox ',
 'India hub ',
 'Echor ',
 'Kraasa ',
 'Numenzo ',
 'BRUTON ',
 'T-ROCK ',
 'Magnolia ',
 'Trendmode ',
 'RapidBox ',
 'Noztile ',
 'WHITE WALKERS ',
 'SPARX ',
 'RapidBox ',
 'KNIGHT WALKERS ',
 'DRESTA ',
 'Chevit ',
 'BIRDE ',
 'EMPTILE ',
 'CAMPUS ',
 'Extoes ',
 'SHANE Internation ',
 'BIRDE ',
 'Zorth ',
 'Rzisbo ',
 'Echor ',
 'BIRDE ',
 'Hot & Knot ',
 'Robbie jones ',
 'Bacan ',
 'BRUTON ',
 'DUNKASTON ',
 'SPARX ',
 'luxury fashion ',
 'RODDICK SHOES ',
 'RODDICK SHOES ',
 'WHITE WALKERS ',
 'Numenzo ',
 'Magnolia ',
 'Kzaara ',
 'SPARX ',
 'India hub ',
 'luxury fashion ',
 'Rzisbo ',
 'aadi ',
 'BRUTON ',
 'Red Tape',
 'Nike',
 'Nike',
 'ADIDAS',
 'Red Tape',
 'Red Tape',
 'ALDO',
 'Puma',
 'HRX by Hrithik Roshan',
 'Nike',
 'Nike',
 'ALDO',
 'ALBERTO MORENO',
 'DressBerry',
 'U.S. Polo Assn.',
 'MENGLER',
 'Nike',
 'Street Style Store',
 'DressBerry',
 'HIGHLANDER',
 'U.S. Polo Assn.',
 'Red Tape',
 'Red Tape',
 'Nike',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'Geox',
 'ALDO',
 'Nike',
 'Puma',
 'ALDO',
 'ALDO',
 'Puma',
 'Puma',
 'Hush Puppies',
 'Nike',
 'Hush Puppies',
 'Hush Puppies',
 'Puma',
 'Puma',
 'Hush Puppies',
 'ASICS',
 'Clarks',
 'Puma',
 'Tommy Hilfiger',
 'Columbia',
 'Hush Puppies',
 'Clarks',
 'J.FONTINI',
 'RARE RABBIT',
 'DAVINCHI',
 'ALDO',
 'TRIBAN By Decathlon',
 'Columbia',
 'Saint G',
 'Clarks',
 'Saint G',
 'Geox',
 'Geox',
 'J.FONTINI',
 'Geox',
 'Hush Puppies',
 'ALDO',
 'DAVINCHI',
 'DAVINCHI',
 'Saint G',
 'Geox',
 'Saint G',
 'Saint G',
 'Cole Haan',
 'Geox',
 'Sole To Soul',
 'Sole To Soul',
 'ROSSO BRUNELLO',
 'Sole To Soul',
 'FILA',
 'Sole To Soul',
 'Sole To Soul',
 'ROSSO BRUNELLO',
 'Clarks',
 'Clarks',
 'New Balance',
 'Columbia',
 'Columbia',
 'Bugatti',
 'Churchill & Company',
 'Bugatti',
 'Bugatti',
 'Geox',
 'Cole Haan',
 'Cole Haan',
 'J.FONTINI',
 'J.FONTINI',
 'Cobblerz',
 'Saint G',
 'Xtep',
 'Geox',
 'Heel & Buckle London',
 'Cole Haan',
 'Cole Haan',
 'Geox',
 'Cole Haan',
 'Royal Enfield',
 'ASICS',
 'Saint G',
 'Saint G',
 'J.FONTINI',
 'Saint G',
 'Saint G',
 'Sole To Soul',
 'Bugatti',
 'J.FONTINI',
 'Pavers England',
 'ALDO',
 'ALDO',
 'Nike',
 'Puma',
 'ALDO',
 'ALDO',
 'Puma',
 'Puma',
 'Hush Puppies',
 'Nike',
 'Hush Puppies',
 'Hush Puppies',
 'Puma',
 'Puma',
 'Hush Puppies',
 'ASICS',
 'Clarks',
 'Puma',
 'Tommy Hilfiger',
 'Columbia',
 'Hush Puppies',
 'Clarks',
 'J.FONTINI',
 'RARE RABBIT',
 'DAVINCHI',
 'ALDO',
 'TRIBAN By Decathlon',
 'Columbia',
 'Saint G',
 'Clarks',
 'Saint G',
 'Geox',
 'Geox',
 'J.FONTINI',
 'Geox',
 'Hush Puppies',
 'ALDO',
 'DAVINCHI',
 'DAVINCHI',
 'Saint G',
 'Geox',
 'Saint G',
 'Saint G',
 'Cole Haan',
 'Geox',
 'Sole To Soul',
 'Sole To Soul',
 'ROSSO BRUNELLO',
 'Sole To Soul',
 'FILA',
 'Sole To Soul',
 'Sole To Soul',
 'ROSSO BRUNELLO',
 'Clarks',
 'Clarks',
 'New Balance',
 'Columbia',
 'Columbia',
 'Bugatti',
 'Churchill & Company',
 'Bugatti',
 'Bugatti',
 'Geox',
 'Cole Haan',
 'Cole Haan',
 'J.FONTINI',
 'J.FONTINI',
 'Cobblerz',
 'Saint G',
 'Xtep',
 'Geox',
 'Heel & Buckle London',
 'Cole Haan',
 'Cole Haan',
 'Geox',
 'Cole Haan',
 'Royal Enfield',
 'ASICS',
 'Saint G',
 'Saint G',
 'J.FONTINI',
 'Saint G',
 'Saint G',
 'Sole To Soul',
 'Bugatti',
 'J.FONTINI',
 'Pavers England',
 'Saint G',
 'Saint G',
 'Saint G',
 'DAVINCHI',
 'ALDO',
 'ALDO',
 'Nike',
 'Puma',
 'ALDO',
 'ALDO',
 'Puma',
 'Puma',
 'Hush Puppies',
 'Nike',
 'Hush Puppies',
 'Hush Puppies',
 'Puma',
 'Puma',
 'Hush Puppies',
 'ASICS',
 'Clarks',
 'Puma',
 'Tommy Hilfiger',
 'Columbia',
 'Hush Puppies',
 'Clarks',
 'J.FONTINI',
 'RARE RABBIT',
 'DAVINCHI',
 'ALDO',
 'TRIBAN By Decathlon',
 'Columbia',
 'Saint G',
 'Clarks',
 'Saint G',
 'Geox',
 'Geox',
 'J.FONTINI',
 'Geox',
 'Hush Puppies',
 'ALDO',
 'DAVINCHI',
 'DAVINCHI',
 'Saint G',
 'Geox',
 'Saint G',
 'Saint G',
 'Cole Haan',
 'Geox',
 'Sole To Soul',
 'Sole To Soul',
 'ROSSO BRUNELLO',
 'Sole To Soul',
 'FILA',
 'Sole To Soul',
 'Sole To Soul',
 'ROSSO BRUNELLO',
 'Clarks',
 'Clarks',
 'New Balance',
 'Columbia',
 'Columbia',
 'Bugatti',
 'Churchill & Company',
 'Bugatti',
 'Bugatti',
 'Geox',
 'Cole Haan',
 'Cole Haan',
 'J.FONTINI',
 'J.FONTINI',
 'Cobblerz',
 'Saint G',
 'Xtep',
 'Geox',
 'Heel & Buckle London',
 'Cole Haan',
 'ALDO',
 'Nike',
 'Puma',
 'ALDO',
 'ALDO',
 'Puma',
 'Puma',
 'Hush Puppies',
 'Nike',
 'Hush Puppies',
 'Hush Puppies',
 'Puma',
 'Puma',
 'Hush Puppies',
 'ASICS',
 'ALDO',
 'Nike',
 'Puma',
 'ALDO',
 'ALDO',
 'Puma',
 'Puma',
 'Hush Puppies',
 'Nike',
 'Hush Puppies',
 'Hush Puppies',
 'Puma',
 'Puma',
 'Hush Puppies',
 'ASICS',
 'Clarks',
 'Puma',
 'Tommy Hilfiger',
 'Columbia',
 'Hush Puppies',
 'Clarks',
 'J.FONTINI',
 'RARE RABBIT',
 'DAVINCHI',
 'Null',
 'TRIBAN By Decathlon',
 'Columbia',
 'Saint G',
 'Clarks',
 'Saint G',
 'Null',
 'Geox',
 'J.FONTINI',
 'Geox',
 'Null',
 'ALDO',
 'Null',
 'DAVINCHI',
 'Saint G',
 'Geox',
 'Saint G',
 'Saint G',
 'Cole Haan',
 'Geox',
 'Sole To Soul',
 'Sole To Soul',
 'ROSSO BRUNELLO',
 'Sole To Soul',
 'FILA',
 'Sole To Soul',
 'Sole To Soul',
 'ROSSO BRUNELLO',
 'Clarks',
 'Clarks',
 'New Balance',
 'Columbia',
 'Columbia',
 'Bugatti',
 'Churchill & Company',
 'Bugatti',
 'Bugatti',
 'Geox',
 'Cole Haan',
 'Cole Haan',
 'J.FONTINI',
 'J.FONTINI',
 'Cobblerz',
 'Saint G',
 'Xtep',
 'Geox',
 'Heel & Buckle London',
 'Cole Haan',
 'Cole Haan',
 'Geox',
 'Cole Haan',
 'Royal Enfield',
 'ASICS',
 'Saint G',
 'Saint G',
 'J.FONTINI',
 'Saint G',
 'Saint G',
 'Sole To Soul',
 'Bugatti',
 'J.FONTINI',
 'Pavers England',
 'Saint G',
 'Saint G',
 'Saint G',
 'DAVINCHI',
 'Saint G',
 'Saint G',
 'J.FONTINI',
 'Saint G',
 'Null',
 'Saint G',
 'Saint G',
 'DAVINCHI',
 'DAVINCHI',
 'Saint G']

In [199]:
print('\033[1m'+'Product_Description :'+'\033[0m')
Product_Description

Product_Description :

['Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Sneakers For Men  (Grey)',
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers Outdoor Loafer Sports for Running Rock Climbing Gym Shoes Sneakers For Men Sneakers For Men  (Grey, Navy)',
 'Modern Trendy Sneakers Shoes Sneakers For Men  (Orange, Grey)',
 'Sneakers Sneakers For Men  (Black, White)',
 '5011-Latest Collection Stylish Casual Loafer Sneakers Shoes For Men Sneakers For Men  (Red)',
 'Stylish & Trendy Sneakers For Men  (White)',
 'Sneaker Sneakers For Men  (Blue, Orange)',
 'Kwik FIT casual sneaker shoes and partywear shoes Casuals For Men Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Luxury Fashionable casual shoes Sneakers For Men  (White)',
 'STYLISH MENS BLACK AND WHITE SNEAKER Sneakers For Men  (Black, White)',
 'Sneakers For Men  (Grey)',
 'Stylish Comfortable Lightweight, Breathable Running Shoes For Men Sneakers For Men  (Black)',
 'Series 7 Sneakers For Men  (White)',
 "Casual , Partywear Sneakers Shoes For Men's And Boys White Color Sneakers For Men  (White)",
 'casual sneakers shoes For Mens Multicolor Combo(MR)-1794-1720 (Pack of 2) Sneakers For Men  (Multicolor)',
 'Sneakers For Men  (Green)',
 "White Sneaker For Men's/Boy's Sneakers For Men  (White)",
 'Sneakers For Men  (White)',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For Men  (Multicolor)',
 'X-Ray 2 Square Sneakers For Men  (Grey)',
 'Modern & Trendy Collection Combo Pack of 02 Shoes for Men Casual Sneakers & Outdoor Walking Shoes for Men Sport Shoes for Men Running Gym Cycling & Trekking Rock Climbing Shoes for Men Sneakers For Men  (Multicolor)',
 'Sneakers For Men  (Black)',
 'Sneakers For Men  (White)',
 'Sneakers For Men  (Brown)',
 'Luxury Fashionable casual sneaker shoes Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Casual Sneakrs For Men Sneakers For Men  (Green, Khaki)',
 "Echor Men's Sneakers Fashion Lightweight Running Shoes Tennis Casual Shoes for Walking Sneakers For Men  (Red)",
 'Sneakers For Men  (White)',
 'Null',
 'Lattest Sneakers Shoe Sneakers For Men  (Black)',
 'Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Sneakers For Men  (Black)',
 'Sneakers For Men  (White)',
 'Sneakers For Men  (Green)',
 'Sneakers For Men  (Black)',
 "Perfect Sports Shoes for Men's Running ,Cycling & Trekking Sneakers For Men's Sneakers For Men  (Black)",
 'Sneakers For Men  (Grey)',
 'Sneakers For Men  (White)',
 '411 Casual Sneakers For Men  (Black)',
 "Casual , Partywear Sneakers Shoes For Men's And Boys White Color Sneakers For Men  (White)",
 'Sneakers For Men  (White)',
 'Luxury Fashionable casual shoes Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Rigel Sneakers For Men  (Black)',
 'Sneakers For Men  (Olive)',
 'Sneakers For Men  (White)',
 'sports shoes for men | Latest Stylish Casual sneakers for men | Lace up lightweight shoes for running, walking, gym, trekking, hiking & party Running Shoes For Men | Running Shoes For Men (Black) Sneakers For Men  (Multicolor)',
 'Skypy-31 Walking Shoes,Training Shoes,Sneakers,Loafers,Canvas Shoes,Casual Shoes,Sneakers Sneakers For Men  (Grey)',
 'Sneakers For Men  (White)',
 'Luxury Fashionable casual sneaker shoes Sneakers For Men  (White)',
 "Men's Sneakers Fashion Lightweight Running Shoes Tennis Casual Shoes for Walking Sneakers For Men  (Blue)",
 'Shark-41 Sneakers For Men  (Grey)',
 'Sneakers For Men  (White)',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For Men  (Multicolor)',
 'Stylish White Casual Sneakers shoes Men and Boys Sneakers For Men  (White, Black)',
 'Sneakers For Men  (Blue)',
 'Sneakers For Men  (Blue)',
 'Stylish & Trendy Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Stylish & Trending Outdoor Walking Comfortable Sneakers For Men  (White)',
 'SM-439 Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 "Original Luxury Branded Fashionable Men's Casual Walking Partywear Sneakers Running White & Black Shoes Sneakers For Men (White&Black) Sneakers For Men (White) Sneakers For Men  (Black)",
 '516 Trendy Star Perfect Sneakers For Men  (Grey)',
 'Stylish Comfortable Lightweight, Breathable Running Shoes For Men Sneakers For Men  (Black)',
 'all white heartbeat casual shoe Sneakers For Men  (White)',
 'EXPLORE Sneakers For Men  (Black)',
 'Sneakers For Men  (Green)',
 'Sneakers For Men  (Green)',
 'Sports Running Shoes Sneakers For Men  (Blue)',
 'New Fashion Outdoor Trendy Lightweight Casual,Canvas Stylish Partywear Sneakers Shoes Boys Sneakers For Men  (Black)',
 'Sneakers For Men  (Gold)',
 "Echor Men's Sneakers Fashion Lightweight Running Shoes Tennis Casual Shoes for Walking Sneakers For Men  (Red)",
 'Stylish and Trendy New Design Lightweight,Casual shoes Sneakers For Men  (Yellow)',
 'High Top Casual Party Wear Boot Stylish Sneakers For Men  (Black)',
 'Casual Sneakers White Shoes For Men Sneakers For Men  (White)',
 'Sneakers For Men  (White)',
 'Modern & Trendy Collection Combo Pack of 02 Shoes for Men Casual Sneakers & Outdoor Walking Shoes for Men Sport Shoes for Men Running Gym Cycling & Trekking Rock Climbing Shoes for Men Sneakers For Men  (Multicolor)',
 'Sneakers For Men  (White)',
 'SM-175 Sneakers For Men  (Black, Red)',
 'Luxury Fashionable casual shoes Sneakers For Men  (White)',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Evening Walk Running Shoes For Men Sneakers For Men  (White, Green)',
 'Fashion Outdoor Canvas Casual Light Weight Lace-up Evening Walk Running Shoes For Men Sneakers For Men  (White, Orange)',
 'Sneakers For Men  (Black)',
 'Sneakers For Men  (White)',
 'Sneakers For Men  (Black)',
 "Kzaara Sneakers Casual Canvas shoes | Branded Stylish Outdoor Trendy shoes for Men | Men's Shoes with no pasting issues | Running Walking Sports shoes | Sneakers Sneakers For Men  (Green, Black)",
 'SM-607 Sneakers For Men  (White, Black)',
 'Luxury Fashionable casual sneaker shoes Sneakers For Men  (White)',
 'Fashionable sneaker shoes Sneakers For Men  (Blue)',
 'Sneakers For Men  (Grey)',
 'Sneakers For Men  (Black, White)',
 'Combo Pack Of 4 Casual Shoes Loafer Shoes Sneakers For Men  (Multicolor)',
 'Men Black Mesh Walking Shoes',
 'Kids Black Revolution 4 Running Shoes',
 'Men Black & Orange Quest 3 Running Shoes',
 'Men Black & Blue Perforated & Striped Adi Streak Running Shoes',
 'Men Black Mesh Sport Shoes',
 'Men Black Mesh Walking Shoes',
 'Men Black Leather Loafers',
 'Men Black Mesh Running Shoes',
 'Men Black Woven Design Atom Running Shoes',
 'Men Black LEGEND ESSENTIAL 2 Training Shoes',
 'Men Black Renew Retaliation Training Shoes',
 'Men Black & Blue Printed Sneakers',
 'Men Black Loafers',
 'Women Black Solid Ballerinas',
 'Men Black & Brown Colourblocked Sneakers',
 'Men Black Textile Walking Shoes',
 'Men Black Zoom Winflo 7 Running Shoes',
 'Women Black Suede High-Top Flat Boots',
 'Women Black Solid Perforated Open Toe Flats',
 'Men Black Solid Sneakers',
 'Men Black LEBRON 2.0 Walking Shoes',
 'Men Black Walking Shoes',
 'Men Black Mesh Walking Non-Marking Shoes',
 'Men Black Vapor Lite Hard Court Tennis Shoes',
 'Men Black Leather Loafers',
 'Men Black Striped Leather Sneakers',
 'Men Black Leather Formal Derbys',
 'Women Black Textured Leather Pumps',
 'Women Black Solid Leather Pumps',
 'Men Black Leather Driving Shoes',
 'Women Black Solid Leather Pumps',
 'Women Black Solid Leather Ballerinas',
 'Men Black Leather Loafers',
 'Black Leather High-Top Platform Heeled Boots',
 'Women Black Leather Loafers',
 'Women Black Leather Slip-On Sneakers',
 'Women Black Leather Slip-On Sneakers',
 'Women Black Basketweave-Textured Leather T-Strap Flats',
 'Women Black Woven Design Chunky Sneakers',
 'Women Black Leather Solid Pumps',
 'Men Black Sneakers',
 'Men Black Leather Formal Slip-Ons',
 'Men Black Solid Leather Formal Derbys',
 'Women Black Leather High-Top Block Heeled Boots with Buckles',
 'Women Black Leather Sneakers',
 'Men Black Textured Leather Formal Brogues',
 'Men Black Solid Leather Formal Derbys',
 'Men Black & Yellow Printed Slip-On Sneakers',
 'Men Black Leather Driving Shoes',
 'Men Black Textured Leather Driving Shoes',
 'Men Black Solid Leather Sneakers',
 'Men Black Solid Leather Formal Oxfords',
 'Women Black Leather Platform Sandals',
 'Men Black Leather Formal Brogues',
 'Men Black Leather Flat Boots',
 'Men Black & Blue Printed Sneakers',
 'Men Black Zoom Winflo 7 Running Shoes',
 'Men Black Electrify Nitro Turn Running Shoes',
 'Men Black Leather Driving Shoes',
 'Men Black Woven Design Sneakers',
 'Men Black Jamming 2.0 Running Shoes',
 'Men Black Eternity Nitro Running Shoes',
 'Men Black Solid Leather Formal Slip-Ons',
 'Men Black Solid Air Max Dawn Next Nature Regular Sneakers with LED Lights',
 'Men Black Solid Leather Formal Slip-Ons',
 'Men Black Solid Formal Derbys',
 'Women Black Textile Eternity NITRO Running Shoes',
 'Men Black Blue FUSE FM Utility Training or Gym Shoes',
 'Men Black Solid Leather Formal Derbys',
 'Women Black Running GEL-Pulse 13 Non-Marking Shoes',
 'Men Black Solid Formal Leather Derbys',
 'Women Black Velocity NITRO Running Shoes',
 'Men Black Solid Leather Regular Sneakers with Cleats',
 'Men Black FACET 60 OUTDRY Waterproof Non-Marking Trekking Shoes',
 'Men Black Solid Formal Slip-Ons',
 'Men Black Solid Leather Formal Loafers',
 'Men Black Loafers',
 'Men Black Leather Flat Boots',
 'Men Black Textured Formal Leather Loafers',
 'Black Wedge Sandals',
 'Unisex Black Textile Training or Gym Non-Marking Cycling Shoes',
 'Women Black & Purple REDMOND V2 MID WP Trekking Non-Marking Shoes',
 'Women Black & Gold-Toned Solid Leather Block Heels',
 'Men Black Leather Derbys',
 'Men Black Solid Mid-Top Chelsea Boots',
 'Men Black Leather Loafers',
 'Men Black Striped Leather Sneakers',
 'J FONTINI Men Black Solid Leather Loafers',
 'Men Black Leather Formal Derbys',
 'Men Black Perforations Leather Slip-On Sneakers',
 'Black Leather Slim Heels',
 'Men Black Solid Formal Leather Slip-On Shoes',
 'Ustraa black',
 'Black Leather Block Heeled Boots',
 'Women Black Textured Leather Pumps',
 'Black Suede Party High-Top Block Heeled Boots',
 'Black Striped Suede Flatform Heeled Boots',
 'Women Black Leather Sneakers',
 'Women Black Solid Leather Pumps',
 'Black Suede High-Top Block Heeled Boots',
 'Black High-Top Block Heeled Boots',
 'Black Printed PU Kitten Sandals',
 'Black Suede High-Top Block Heeled Boots',
 'Women Black Leather Sneakers',
 'Black High-Top Comfort Heeled Boots',
 'Black High-Top Comfort Heeled Boots',
 'Black PU Block Pumps with Buckles',
 'Women Black Solid Leather Slip-On Ballerinas',
 'Women Black Solid Leather Ballerina',
 'Women Black Striped Woven Design Running Shoes',
 'Women Black PEAKFREAK XCRSN II XCEL LOW OUTDRY Trekking Non-Marking Shoes',
 'Women Black & Grey PEAKFREAK X2 OUTDRY Trekking Non-Marking Shoes',
 'Men Black Solid Formal Oxfords',
 'Men Black Solid Leather Formal Monks',
 'Men Black Textile Walking Non-Marking Shoes',
 'Men Black Solid Leather Formal Derbys',
 'Men Black Leather Driving Shoes',
 'Men Black Originalgrand Stitchlite Wingtip Oxford Sneakers',
 'Men Black Generation ZeroGrand Stitchlite Sneakers',
 'Men Black Leather Loafers',
 'Men Black Leather Loafers',
 'Men Black Textured Leather Formal Derbys',
 'Women Black Woven Leather Block Heel Mules',
 'Men Black & Lime Green Textile Running Non-Marking X-Corese Shoes',
 'Women Black Solid Leather Pumps',
 'Men Black Solid Formal Leather Derby',
 'Women Black Solid Leather Open Toe Flats',
 'Women Black Lightweight Sneakers',
 'Women Black Solid Leather Ballerinas',
 'Women Black Solid Leather Ballerinas',
 'Men Black Leather Cabo WP Riding Boots',
 'Men Black & Grey Colourblocked PU Sneakers',
 'Women Black Leather Block Heeled Boots with Chain Embellishment',
 'Women Black Leather High-Top Block Heeled Boots',
 'Men Black Solid Leather Formal Loafers',
 'Women Black Leather Block Heeled Boots',
 'Black Leather Block Heeled Boots with Buckles',
 'Black & Beige Platform Peep Toes with Buckles',
 'Black Block Heeled Boots',
 'Men Black Textured Leather Formal Loafers',
 'Men Black Leather Tassel Driving Shoes',
 'Men Black & Blue Printed Sneakers',
 'Men Black & Blue Printed Sneakers',
 'Men Black Zoom Winflo 7 Running Shoes',
 'Men Black Electrify Nitro Turn Running Shoes',
 'Men Black Leather Driving Shoes',
 'Men Black Woven Design Sneakers',
 'Men Black Jamming 2.0 Running Shoes',
 'Men Black Eternity Nitro Running Shoes',
 'Men Black Solid Leather Formal Slip-Ons',
 'Men Black Solid Air Max Dawn Next Nature Regular Sneakers with LED Lights',
 'Men Black Solid Leather Formal Slip-Ons',
 'Men Black Solid Formal Derbys',
 'Women Black Textile Eternity NITRO Running Shoes',
 'Men Black Blue FUSE FM Utility Training or Gym Shoes',
 'Men Black Solid Leather Formal Derbys',
 'Women Black Running GEL-Pulse 13 Non-Marking Shoes',
 'Men Black Solid Formal Leather Derbys',
 'Women Black Velocity NITRO Running Shoes',
 'Men Black Solid Leather Regular Sneakers with Cleats',
 'Men Black FACET 60 OUTDRY Waterproof Non-Marking Trekking Shoes',
 'Men Black Solid Formal Slip-Ons',
 'Men Black Solid Leather Formal Loafers',
 'Men Black Loafers',
 'Men Black Leather Flat Boots',
 'Men Black Textured Formal Leather Loafers',
 'Black Wedge Sandals',
 'Unisex Black Textile Training or Gym Non-Marking Cycling Shoes',
 'Women Black & Purple REDMOND V2 MID WP Trekking Non-Marking Shoes',
 'Women Black & Gold-Toned Solid Leather Block Heels',
 'Men Black Leather Derbys',
 'Men Black Solid Mid-Top Chelsea Boots',
 'Men Black Leather Loafers',
 'Men Black Striped Leather Sneakers',
 'J FONTINI Men Black Solid Leather Loafers',
 'Men Black Leather Formal Derbys',
 'Men Black Perforations Leather Slip-On Sneakers',
 'Black Leather Slim Heels',
 'Men Black Solid Formal Leather Slip-On Shoes',
 'Ustraa black',
 'Black Leather Block Heeled Boots',
 'Women Black Textured Leather Pumps',
 'Black Suede Party High-Top Block Heeled Boots',
 'Black Striped Suede Flatform Heeled Boots',
 'Women Black Leather Sneakers',
 'Women Black Solid Leather Pumps',
 'Black Suede High-Top Block Heeled Boots',
 'Black High-Top Block Heeled Boots',
 'Black Printed PU Kitten Sandals',
 'Black Suede High-Top Block Heeled Boots',
 'Women Black Leather Sneakers',
 'Black High-Top Comfort Heeled Boots',
 'Black High-Top Comfort Heeled Boots',
 'Black PU Block Pumps with Buckles',
 'Women Black Solid Leather Slip-On Ballerinas',
 'Women Black Solid Leather Ballerina',
 'Women Black Striped Woven Design Running Shoes',
 'Women Black PEAKFREAK XCRSN II XCEL LOW OUTDRY Trekking Non-Marking Shoes',
 'Women Black & Grey PEAKFREAK X2 OUTDRY Trekking Non-Marking Shoes',
 'Men Black Solid Formal Oxfords',
 'Men Black Solid Leather Formal Monks',
 'Men Black Textile Walking Non-Marking Shoes',
 'Men Black Solid Leather Formal Derbys',
 'Men Black Leather Driving Shoes',
 'Men Black Originalgrand Stitchlite Wingtip Oxford Sneakers',
 'Men Black Generation ZeroGrand Stitchlite Sneakers',
 'Men Black Leather Loafers',
 'Men Black Leather Loafers',
 'Men Black Textured Leather Formal Derbys',
 'Women Black Woven Leather Block Heel Mules',
 'Men Black & Lime Green Textile Running Non-Marking X-Corese Shoes',
 'Women Black Solid Leather Pumps',
 'Men Black Solid Formal Leather Derby',
 'Women Black Solid Leather Open Toe Flats',
 'Women Black Lightweight Sneakers',
 'Women Black Solid Leather Ballerinas',
 'Women Black Solid Leather Ballerinas',
 'Men Black Leather Cabo WP Riding Boots',
 'Men Black & Grey Colourblocked PU Sneakers',
 'Women Black Leather Block Heeled Boots with Chain Embellishment',
 'Women Black Leather High-Top Block Heeled Boots',
 'Men Black Solid Leather Formal Loafers',
 'Women Black Leather Block Heeled Boots',
 'Black Leather Block Heeled Boots with Buckles',
 'Black & Beige Platform Peep Toes with Buckles',
 'Black Block Heeled Boots',
 'Men Black Textured Leather Formal Loafers',
 'Men Black Leather Tassel Driving Shoes',
 'Black Leather Kitten Heeled Boots',
 'Black Leather High-Top Block Heeled Boots',
 'Black Leather Wedge Heeled Boots with Buckles',
 'Men Black Solid Slip On Shoes',
 'Men Black & Blue Printed Sneakers',
 'Men Black & Blue Printed Sneakers',
 'Men Black Zoom Winflo 7 Running Shoes',
 'Men Black Electrify Nitro Turn Running Shoes',
 'Men Black Leather Driving Shoes',
 'Men Black Woven Design Sneakers',
 'Men Black Jamming 2.0 Running Shoes',
 'Men Black Eternity Nitro Running Shoes',
 'Men Black Solid Leather Formal Slip-Ons',
 'Men Black Solid Air Max Dawn Next Nature Regular Sneakers with LED Lights',
 'Men Black Solid Leather Formal Slip-Ons',
 'Men Black Solid Formal Derbys',
 'Women Black Textile Eternity NITRO Running Shoes',
 'Men Black Blue FUSE FM Utility Training or Gym Shoes',
 'Men Black Solid Leather Formal Derbys',
 'Women Black Running GEL-Pulse 13 Non-Marking Shoes',
 'Men Black Solid Formal Leather Derbys',
 'Women Black Velocity NITRO Running Shoes',
 'Men Black Solid Leather Regular Sneakers with Cleats',
 'Men Black FACET 60 OUTDRY Waterproof Non-Marking Trekking Shoes',
 'Men Black Solid Formal Slip-Ons',
 'Men Black Solid Leather Formal Loafers',
 'Men Black Loafers',
 'Men Black Leather Flat Boots',
 'Men Black Textured Formal Leather Loafers',
 'Black Wedge Sandals',
 'Unisex Black Textile Training or Gym Non-Marking Cycling Shoes',
 'Women Black & Purple REDMOND V2 MID WP Trekking Non-Marking Shoes',
 'Women Black & Gold-Toned Solid Leather Block Heels',
 'Men Black Leather Derbys',
 'Men Black Solid Mid-Top Chelsea Boots',
 'Men Black Leather Loafers',
 'Men Black Striped Leather Sneakers',
 'J FONTINI Men Black Solid Leather Loafers',
 'Men Black Leather Formal Derbys',
 'Men Black Perforations Leather Slip-On Sneakers',
 'Black Leather Slim Heels',
 'Men Black Solid Formal Leather Slip-On Shoes',
 'Ustraa black',
 'Black Leather Block Heeled Boots',
 'Women Black Textured Leather Pumps',
 'Black Suede Party High-Top Block Heeled Boots',
 'Black Striped Suede Flatform Heeled Boots',
 'Women Black Leather Sneakers',
 'Women Black Solid Leather Pumps',
 'Black Suede High-Top Block Heeled Boots',
 'Black High-Top Block Heeled Boots',
 'Black Printed PU Kitten Sandals',
 'Black Suede High-Top Block Heeled Boots',
 'Women Black Leather Sneakers',
 'Black High-Top Comfort Heeled Boots',
 'Black High-Top Comfort Heeled Boots',
 'Black PU Block Pumps with Buckles',
 'Women Black Solid Leather Slip-On Ballerinas',
 'Women Black Solid Leather Ballerina',
 'Women Black Striped Woven Design Running Shoes',
 'Women Black PEAKFREAK XCRSN II XCEL LOW OUTDRY Trekking Non-Marking Shoes',
 'Women Black & Grey PEAKFREAK X2 OUTDRY Trekking Non-Marking Shoes',
 'Men Black Solid Formal Oxfords',
 'Men Black Solid Leather Formal Monks',
 'Men Black Textile Walking Non-Marking Shoes',
 'Men Black Solid Leather Formal Derbys',
 'Men Black Leather Driving Shoes',
 'Men Black Originalgrand Stitchlite Wingtip Oxford Sneakers',
 'Men Black Generation ZeroGrand Stitchlite Sneakers',
 'Men Black Leather Loafers',
 'Men Black Leather Loafers',
 'Men Black Textured Leather Formal Derbys',
 'Women Black Woven Leather Block Heel Mules',
 'Men Black & Lime Green Textile Running Non-Marking X-Corese Shoes',
 'Women Black Solid Leather Pumps',
 'Men Black Solid Formal Leather Derby',
 'Women Black Solid Leather Open Toe Flats',
 'Men Black & Blue Printed Sneakers',
 'Men Black Zoom Winflo 7 Running Shoes',
 'Men Black Electrify Nitro Turn Running Shoes',
 'Men Black Leather Driving Shoes',
 'Men Black Woven Design Sneakers',
 'Men Black Jamming 2.0 Running Shoes',
 'Men Black Eternity Nitro Running Shoes',
 'Men Black Solid Leather Formal Slip-Ons',
 'Men Black Solid Air Max Dawn Next Nature Regular Sneakers with LED Lights',
 'Men Black Solid Leather Formal Slip-Ons',
 'Men Black Solid Formal Derbys',
 'Women Black Textile Eternity NITRO Running Shoes',

In [192]:
#printing length
print(len(Brand),len(Product_Description),len(Price))

520 520 520

In [194]:
# creating a dataframe
Shoes=pd.DataFrame({})
Shoes['Brand']=Brand
Shoes['Product_Description']=Product_Description
Shoes['Price']=Price
print('\033[1m'+'Shoes_Dataset :'+'\033[0m')
Shoes

Shoes_Dataset :

        Brand                                Product_Description      Price
0      Bacan                           Sneakers For Men  (White)       ₹476
1    Numenzo                           Sneakers For Men  (White)       ₹599
2     Kzaara                            Sneakers For Men  (Grey)       ₹209
3     Chevit   Super Stylish & Trendy Combo Pack of 02 Pairs ...       ₹469
4     BRUTON   Modern Trendy Sneakers Shoes Sneakers For Men ...       ₹209
..        ...                                                ...        ...
515   Saint G    Black Suede Leather High-Top Block Heeled Boots  Rs. 10625
516   Saint G         Black Suede High-Top Flatform Heeled Boots  Rs. 11475
517  DAVINCHI              Men Black Solid Leather Formal Derbys   Rs. 9990
518  DAVINCHI          Men Black Textured Formal Leather Loafers   Rs. 8990
519   Saint G  Women Black Leather High-Top Block Heeled Boot...   Rs. 8925

[520 rows x 3 columns]

**Q8: Go to webpage https://www.amazon.in/
Enter “Laptop” in the search field and then click the search icon.
Then set CPU Type filter to “Intel Core i7” and “Intel Core i9” as shown in the below image:**


After setting the filters scrape first 10 laptops data. You have to scrape 3 attributesfor each laptop:
1. Title
2. Ratings
3. Price
As shown in the below image as the tick marked attributes.

In [27]:
# specifying the url of the webpage to be scraped
url="https://www.amazon.in/"
driver.get(url)

In [28]:
# Searching laptop in the search bar and clicking the search button
Search_bar=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input")
Search_bar.send_keys("laptop")

# Clicking on the search button
search_btn = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input")
search_btn.click()

In [32]:
# Setting CPU Type filter to "Intel Core i7"
intel_i7 = driver.find_element_by_xpath('//*[@id="p_n_feature_thirteen_browse-bin/12598163031"]/span/a/span')
intel_i7.click()

In [33]:
Laptop_model = []
Price = []
URL = []
Rating = []

In [34]:
# Scraping data for laptop titles
laptop_model = driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']")
for i in laptop_model:
    Laptop_model.append(i.text)
else:
    Laptop_model.append('-')

# Scraping laptop price
price = driver.find_elements_by_xpath("//span[@class='a-price-whole']")
for i in price:
    Price.append(i.text)
else:
    Price.append('-')

In [35]:
# Extracting URL of Laptop
laptop_urls=driver.find_elements_by_xpath('//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
for i in laptop_urls[:10]:
    URL.append(i.get_attribute('href'))

In [36]:
# Extracting the ratings of the laptop from each url
import tqdm
from tqdm import tqdm
for url in tqdm(URL):
    driver.get(url)
    try:   
        laptop_rating=driver.find_element_by_id("acrCustomerReviewText")  #Locating the rating link
        laptop_rating.click()
        # Locating the rating tags
        rating=driver.find_element_by_xpath('//span[@class="a-size-medium a-color-base"]') 
        Rating.append(rating.text)  #Appending the text from tags to the list
    except NoSuchElementException :
        Rating.append('Rating Not Available')

100%|██████████| 10/10 [01:40<00:00, 10.05s/it]

In [37]:
# Creating DataFrame for the scraped data
Laptop_Amazon = pd.DataFrame({})
Laptop_Amazon["Laptop Model"] = Laptop_model[:10]
Laptop_Amazon["Laptop Price"] = Price[:10]
Laptop_Amazon["Laptop Ratings"] = Rating[:10]
Laptop_Amazon

,Laptop Model,Laptop Price,Laptop Ratings
0,"ASUS TUF Gaming F15 (2021), 15.6"" (39.62 cms) ...","89,990",5 out of 5
1,"ASUS VivoBook 14 (2021), 14-inch (35.56 cms) F...","57,490",4.4 out of 5
2,"ASUS VivoBook 14 (2021), 14-inch (35.56 cms) F...","57,490",4.4 out of 5
3,Mi Notebook Ultra 3.2K Resolution Display Inte...,"77,499",4.3 out of 5
4,HP Pavilion x360 11th Gen Intel Core i7 14 inc...,"91,800",4.5 out of 5
5,"ASUS TUF Gaming F15 (2021), 15.6"" (39.62 cms) ...","89,990",5 out of 5
6,"ASUS TUF Dash F15 (2021), 15.6"" (39.62 cms) FH...","1,34,990",5 out of 5
7,"ASUS VivoBook K15 OLED (2021), 15.6-inch (39.6...","82,990",4 out of 5
8,"Dell G15 Intel i7-11800H Gaming Laptop, 16GB D...","1,03,200",Rating Not Available
9,Lenovo IdeaPad 5 Pro 11th Gen Intel Core i7 14...,"80,900",3.5 out of 5

**Q9: Write a python program to scrape data for first 10 job results for Data Scientist Designation in Noida
location. You have to scrape company name, No. of days ago when job was posted, Rating of the company.
This task will be done in following steps:**
1. First get the webpage https://www.ambitionbox.com/
2. Click on the Job option as shown in the image


3. After reaching to the next webpage, In place of “Search by Designations, Companies, Skills” enter “Data Scientist” and click on search button.

4. You will reach to the following web page click on location and in place of “Search location” enter “Noida” and select location “Noida”.

5. Then scrape the data for the first 10 jobs results you get on the above shown page.

6. Finally create a dataframe of the scraped data.

In [1]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')

In [4]:
# connecting Webdriver
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver
#specifying the url of the webpage to be scraped
url="https://www.ambitionbox.com/"
driver.get(url)
time.sleep(3)

In [5]:
#Extracting the element to click on the jobs option
click_jobs = driver.find_element_by_xpath('/html/body/div[1]/nav/nav/a[6]')
#Clicking on jobs option
click_jobs.click()
time.sleep(3)

In [6]:
# Extracting the search element to enter data scientist designation
Search_bar = driver.find_element_by_xpath('/html/body/div/div/div/div[2]/div[1]/div/div/div/div/span/input')
Search_bar.send_keys("Data scientist")

# clicking on search button
search_button = driver.find_element_by_xpath('//*[@id="jobs"]/div[2]/div[1]/div/div/div/button/span')
search_button.click()

In [10]:
#Extracting the element for location button
location_button = driver.find_element_by_xpath('//*[@id="filters-row"]/div/div/div[2]/div[1]/p')
location_button.click()
time.sleep(2)

# Extracting the element fot searching location
location_search = driver.find_element_by_xpath('//*[@id="filters-row"]/div/div/div[2]/div[2]/div/div[2]/input')
# Entering Noida as preferred location
location_search.send_keys("Noida")
time.sleep(2)

# Selecting Noida from drop down list
noida = driver.find_element_by_xpath('//*[@id="filters-row"]/div/div/div[2]/div[2]/div/div[3]/div[1]/div[1]/div/label')
noida.click()

In [14]:
# Creating Empty list for scraping
Company_Title = []
Job_posting_days = []
Rating = []

In [15]:
#Extracting elements for company name
company_Title = driver.find_elements_by_xpath('//div[@class="company-info"]')
for i in company_Title[:10]:
    Company_Title.append(i.text)
else:
    Company_Title.append('Not Available')
    
#Extracting elements for date posted
job_posting_days = driver.find_elements_by_xpath('//span[@class="body-small-l"]')
for i in job_posting_days[:10]:
    Job_posting_days.append(i.text.split()[0])
else:
    Job_posting_days.append('Not Available')

#Extracting elements for rating
ratings = driver.find_elements_by_xpath('//span[@class="body-small"]')
for i in ratings[:10]:
    Rating.append(i.text)
else:
    Rating.append('Not Available')

In [16]:
len(Rating), len(Job_posting_days), len(Company_Title)

(11, 11, 11)

In [18]:
#creating a dataframe and adding columns to it
Ambitionbox_data = pd.DataFrame({'Company Title':Company_Title,'Job posted days':Job_posting_days,'Rating of company':Rating})
Ambitionbox_data[:10]

,Company Title,Job posted days,Rating of company
0,NTT DATA GLOBAL DELIVERY SERVICES PRIVATE LIMI...,7d,3.9
1,NTT DATA GLOBAL DELIVERY SERVICES PRIVATE LIMI...,via,3.8
2,HCL Technologies Limited\n3.8\n(16.2k Reviews),8d,4.1
3,Optum Global Solutions (India) Private Limited...,via,4.2
4,WSP CONSULTANTS INDIA PRIVATE LIMITED\n4.2\n(9...,18d,4.2
5,Microsoft India (R and D) Pvt Ltd\n4.2\n(574 R...,via,3.8
6,HCL Technologies Ltd\n3.8\n(16.2k Reviews),8d,3.9
7,Jubilant Foodworks Limited\n3.9\n(556 Reviews),via,3.8
8,HCL Technologies\n3.8\n(16.2k Reviews),19d,3.8
9,RATEGAIN TRAVEL TECHNOLOGIES LIMITED\n3.8\n(72...,via,3.7

**Q10: Write a python program to scrape the salary data for Data Scientist designation.
You have to scrape Company name, Number of salaries, Average salary, Minsalary, Max Salary.
The above task will be, done as shown in the below steps:**

1. First get the webpage https://www.ambitionbox.com/
2. Click on the salaries option as shown in the image.
3. After reaching to the following webpage, In place of “Search Job Profile” enters “Data Scientist” and then click on “Data Scientist”. You have to scrape the data ticked in the above image.
4. Scrape the data for the first 10 companies. Scrape the company name, total salary record, average
salary, minimum salary, maximum salary, experience required.
5. Store the data in a dataframe.

In [19]:
# connecting Webdriver
driver = webdriver.Chrome(r'C:\chromedriver.exe')
driver
#specifying the url of the webpage to be scraped
url="https://www.ambitionbox.com/"
driver.get(url)
time.sleep(3)

In [20]:
# Extracting the element to click on the salaries option
Salary_button = driver.find_element_by_xpath('//*[@id="headerWrapper"]/nav/nav/a[4]')
Salary_button.click()
time.sleep(3)

In [21]:
#Extracting the search element to enter data scientist designation
Search_bar = driver.find_element_by_xpath('//*[@id="jobProfileSearchbox"]')
Search_bar.send_keys("Data scientist")
time.sleep(1)

# clicking on data scientist designation using the extracted xpath
Datascientist = driver.find_element_by_xpath('//*[@id="salaries"]/main/section[1]/div[2]/div[1]/span/div/div/div[1]/div/div/p')
Datascientist.click()
time.sleep(2)

In [22]:
comp_name = driver.find_elements_by_xpath('//div[@class="name"]/a')
total_salary = driver.find_elements_by_xpath('//div[@class="name"]/span')
avg_salary = driver.find_elements_by_xpath('//p[@class="averageCtc"]')
min_salary = driver.find_elements_by_xpath('//div[@class="value body-medium"]')
max_salary = driver.find_elements_by_xpath('//div[@class="value body-medium"]')
exp = driver.find_elements_by_xpath('//div[@class="salaries sbold-list-header"]')

In [24]:
# Creating Empty list
Company_Title = []
Total_salary = []
Avg_salary = []
Min_salary = []
Max_salary = []
Experience = []

In [25]:
for i in comp_name:
    Company_Title.append(i.text)
    
for i in total_salary:
    Total_salary.append(i.text)
    
for i in avg_salary:
    Avg_salary.append(i.text)
    
for i in range(0,len(min_salary),2):
    Min_salary.append(min_salary[i].text)
    
for i in range(1,len(min_salary),2):
    Min_salary.append(min_salary[i].text)

for i in exp:
    Experience.append(i.text.split()[3:])

In [26]:
Salary_Data = pd.DataFrame({'Company Name':Company_Title[:10],'No. of Salaries':Total_salary[:10],'Average Salary':Avg_salary[:10],
                  'Minimum Salary':Min_salary[:10],'Maximum Salary':Min_salary[:10],'Experience Required':Experience[:10]})
Salary_Data

,Company Name,No. of Salaries,Average Salary,Minimum Salary,Maximum Salary,Experience Required
0,Ab Inbev,based on 28 salaries,₹ 20.3L,₹ 15.0L,₹ 15.0L,"[3-4, yrs, exp]"
1,ZS,based on 15 salaries,₹ 15.3L,₹ 9.5L,₹ 9.5L,"[2, yrs, exp]"
2,Optum,based on 25 salaries,₹ 15.1L,₹ 11.0L,₹ 11.0L,"[3-4, yrs, exp]"
3,Fractal Analytics,based on 77 salaries,₹ 15.1L,₹ 9.5L,₹ 9.5L,"[2-4, yrs, exp]"
4,Tiger Analytics,based on 33 salaries,₹ 14.4L,₹ 8.3L,₹ 8.3L,"[3-4, yrs, exp]"
5,UnitedHealth,based on 52 salaries,₹ 13.9L,₹ 8.3L,₹ 8.3L,"[2-4, yrs, exp]"
6,Verizon,based on 14 salaries,₹ 12.7L,₹ 10.0L,₹ 10.0L,"[4, yrs, exp]"
7,Ganit Business Solutions,based on 13 salaries,₹ 12.4L,₹ 8.5L,₹ 8.5L,"[4, yrs, exp]"
8,Ericsson,based on 43 salaries,₹ 11.9L,₹ 5.8L,₹ 5.8L,"[3-4, yrs, exp]"
9,Deloitte,based on 57 salaries,₹ 11.7L,₹ 6.9L,₹ 6.9L,"[2-4, yrs, exp]"